In [ ]:
import pandas as pd
df_tour = pd.read_csv('./data/여행지.csv')

In [61]:
df_tour

,id,lclas,mlsfc,id_poi,poi_nm,branch_nm,sub_nm,mcate_cd,mcate_nm,pnu,...,rd_cd,rd_nm,bld_num,x,y,grid_cd,lst_updt_dt,data_orgn,FILE_NAME,base_ymd
0,KCLANPO25N000000001,장소,관광지,10000051,덕수궁중명전,NaN,NaN,60603,유명사적/유적지,1.114017e+18,...,NaN,NaN,NaN,126.972512,37.566707,다사534520,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
1,KCLANPO25N000000002,장소,관광지,10000141,마애여래좌상,NaN,NaN,60604,국보,4.792031e+18,...,NaN,NaN,NaN,128.736928,36.931296,마바101821,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
2,KCLANPO25N000000003,장소,관광지,10000211,추월산관광지,NaN,NaN,60513,일반관광지,4.671038e+18,...,NaN,NaN,NaN,126.997724,35.401730,다마543118,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
3,KCLANPO25N000000004,장소,관광지,10017022,선우이엔지,NaN,NaN,60403,항공사/여행사,4.161025e+18,...,4.161032e+11,현산로,94,127.291678,37.395739,다사815329,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
4,KCLANPO25N000000005,장소,관광지,10051323,산머루농원오토캠핑장,NaN,NaN,60520,캠핑장,4.148037e+18,...,4.148044e+11,윗배우니길,441-42,126.960906,37.958494,다사526955,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53881,KCLANPO25N000053882,장소,관광지,9654213,용소폭포,NaN,NaN,60504,폭포/계곡,5.175025e+18,...,NaN,NaN,NaN,128.570155,37.185208,라사949101,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
53882,KCLANPO25N000053883,장소,관광지,9654216,삼척대이리굴피집,NaN,NaN,60603,유명사적/유적지,5.123036e+18,...,NaN,NaN,NaN,129.014415,37.323768,마사341260,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
53883,KCLANPO25N000053884,장소,관광지,9654220,백전리물레방아,NaN,NaN,60607,천연기념물,5.177036e+18,...,NaN,NaN,NaN,128.898136,37.246240,마사240172,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
53884,KCLANPO25N000053885,장소,관광지,9654221,곡운구곡,NaN,NaN,60504,폭포/계곡,5.179034e+18,...,NaN,NaN,NaN,127.539121,38.053222,라아034059,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822
53885,KCLANPO25N000053886,장소,관광지,9654223,펀치볼전적비,NaN,NaN,60606,비/탑/문/각,5.180032e+18,...,NaN,NaN,NaN,128.045385,38.215918,라아477240,20251027,맵퍼스,KC_495_LLR_ATRCTN_2025,20250822

In [62]:
cols_to_drop = [
    'id', 'lclas', 'mlsfc', 'id_poi', 'branch_nm', 'sub_nm', 
    'mcate_cd', 'pnu', 'bemd_nm', 'ri_nm', 'beonji', 
    'badm_cd', 'hadm_cd', 'rd_cd', 'rd_nm', 'bld_num', 
    'grid_cd', 'lst_updt_dt', 'data_orgn', 'FILE_NAME', 'base_ymd'
]
df_tour = df_tour.drop(columns=cols_to_drop, errors='ignore')

In [63]:
df_tour

           poi_nm  mcate_nm  sido_nm sgg_nm           x          y
0          덕수궁중명전  유명사적/유적지    서울특별시     중구  126.972512  37.566707
1          마애여래좌상        국보     경상북도    봉화군  128.736928  36.931296
2          추월산관광지     일반관광지     전라남도    담양군  126.997724  35.401730
3           선우이엔지   항공사/여행사      경기도    광주시  127.291678  37.395739
4      산머루농원오토캠핑장       캠핑장      경기도    파주시  126.960906  37.958494
...           ...       ...      ...    ...         ...        ...
53881        용소폭포     폭포/계곡  강원특별자치도    영월군  128.570155  37.185208
53882    삼척대이리굴피집  유명사적/유적지  강원특별자치도    삼척시  129.014415  37.323768
53883     백전리물레방아     천연기념물  강원특별자치도    정선군  128.898136  37.246240
53884        곡운구곡     폭포/계곡  강원특별자치도    화천군  127.539121  38.053222
53885      펀치볼전적비   비/탑/문/각  강원특별자치도    양구군  128.045385  38.215918

[53886 rows x 6 columns]

In [ ]:
pet_df = pd.read_csv("./data/pet_tour_data.csv")

In [65]:
# 1. 삭제할 컬럼 리스트 정의 
cols_to_drop = [
    'addr2', 'areacode', 'cat1', 'cat2', 'cat3', 'contentid', 
 'createdtime', 'firstimage', 'tel', 
    'showflag', 'lDongRegnCd', 'lDongSignguCd', 
    'lclsSystm1', 'lclsSystm2', 'lclsSystm3', 'firstimage2', 'cpyrhtDivCd', 'mlevel', 'modifiedtime', 'sigungucode' 
]

# 2. 컬럼 삭제 실행
pet_df = pet_df.drop(columns=cols_to_drop, errors='ignore')

In [66]:
pet_df

,addr1,contenttypeid,mapx,mapy,title,zipcode
0,부산광역시 부산진구 가야대로 779 (부전동),38,129.056806,35.157955,가까운약국,47257
1,서울특별시 중구 명동8가길 33 (충무로2가),38,126.986903,37.561912,가나안경원 명동점,04537
2,서울특별시 강서구 마곡동로 166 (마곡동),38,126.836784,37.569092,가든뷰,07790
3,서울특별시 중구 장충단로13길 20 (을지로6가),38,127.007666,37.568735,가버 현대아울렛 동대문점,04563
4,경상북도 성주군 수륜면 봉양로1길 313,12,128.153738,35.834072,가야산생태탐방원,40064
...,...,...,...,...,...,...
10195,서울특별시 성북구 성북동,28,127.006816,37.569354,[북악하늘길 스카이웨이] 하늘한마당~하늘마루,02834
10196,전북특별자치도 진안군 주천면 대불리,28,127.388516,35.982744,[진안고원길 9구간] 운일암반일암 숲길,55400
10197,충청북도 충주시 종민동,12,127.996554,36.978641,[충주 풍경길] 종댕이길,27484
10198,강원특별자치도 양양군 손양면 수산리,28,128.672327,38.080057,[해파랑길] 44코스,25042
10199,강원특별자치도 속초시 동해대로 3664,28,128.608558,38.163207,[해파랑길] 45코스,24902

In [67]:
import pandas as pd

# 1. 분리 로직 함수 정의
def split_korea_addr(addr):
    if not addr or pd.isna(addr):
        return "미분류", "미분류"
    
    parts = str(addr).split()
    
    sido = parts[0] if len(parts) > 0 else "미분류"
    
    sgg = parts[1] if len(parts) > 1 else ""
    
    return sido, sgg

# 2. 새로운 컬럼 생성 (sido_nm, sgg_nm)
pet_df[['sido_nm', 'sgg_nm']] = pet_df['addr1'].apply(
    lambda x: pd.Series(split_korea_addr(x))
)

# 3. 컬럼 순서 재배치 및 불필요 컬럼 삭제.
final_cols = ['title', 'sido_nm', 'sgg_nm', 'mapx', 'mapy', 'zipcode', 'contenttypeid']
pet_df = pet_df[final_cols]

In [68]:
# 1. 변환용 딕셔너리 생성
content_type_map = {
    '12': '관광지',
    '14': '문화시설',
    '15': '축제공연행사',
    '28': '레포츠',
    '32': '숙박',
    '38': '쇼핑',
    '39': '음식점'
}

# 2. 데이터 타입 맞추기 
pet_df['contenttypeid'] = pet_df['contenttypeid'].astype(str)

pet_df['content_type_nm'] = pet_df['contenttypeid'].map(content_type_map).fillna('기타')

if 'content_type_nm' in pet_df.columns:
    pet_df = pet_df.drop(columns=['contenttypeid'], errors='ignore')
    
    cols = ['title', 'content_type_nm', 'sido_nm', 'sgg_nm'] + [c for c in pet_df.columns if c not in ['title', 'content_type_nm', 'sido_nm', 'sgg_nm']]
    pet_df = pet_df[cols]

C:\Users\playdata2\AppData\Local\Temp\ipykernel_9412\1776002720.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pet_df['contenttypeid'] = pet_df['contenttypeid'].astype(str)

In [69]:
df_tour

           poi_nm  mcate_nm  sido_nm sgg_nm           x          y
0          덕수궁중명전  유명사적/유적지    서울특별시     중구  126.972512  37.566707
1          마애여래좌상        국보     경상북도    봉화군  128.736928  36.931296
2          추월산관광지     일반관광지     전라남도    담양군  126.997724  35.401730
3           선우이엔지   항공사/여행사      경기도    광주시  127.291678  37.395739
4      산머루농원오토캠핑장       캠핑장      경기도    파주시  126.960906  37.958494
...           ...       ...      ...    ...         ...        ...
53881        용소폭포     폭포/계곡  강원특별자치도    영월군  128.570155  37.185208
53882    삼척대이리굴피집  유명사적/유적지  강원특별자치도    삼척시  129.014415  37.323768
53883     백전리물레방아     천연기념물  강원특별자치도    정선군  128.898136  37.246240
53884        곡운구곡     폭포/계곡  강원특별자치도    화천군  127.539121  38.053222
53885      펀치볼전적비   비/탑/문/각  강원특별자치도    양구군  128.045385  38.215918

[53886 rows x 6 columns]

In [70]:
pet_df

,title,content_type_nm,sido_nm,sgg_nm,mapx,mapy,zipcode
0,가까운약국,쇼핑,부산광역시,부산진구,129.056806,35.157955,47257
1,가나안경원 명동점,쇼핑,서울특별시,중구,126.986903,37.561912,04537
2,가든뷰,쇼핑,서울특별시,강서구,126.836784,37.569092,07790
3,가버 현대아울렛 동대문점,쇼핑,서울특별시,중구,127.007666,37.568735,04563
4,가야산생태탐방원,관광지,경상북도,성주군,128.153738,35.834072,40064
...,...,...,...,...,...,...,...
10195,[북악하늘길 스카이웨이] 하늘한마당~하늘마루,레포츠,서울특별시,성북구,127.006816,37.569354,02834
10196,[진안고원길 9구간] 운일암반일암 숲길,레포츠,전북특별자치도,진안군,127.388516,35.982744,55400
10197,[충주 풍경길] 종댕이길,관광지,충청북도,충주시,127.996554,36.978641,27484
10198,[해파랑길] 44코스,레포츠,강원특별자치도,양양군,128.672327,38.080057,25042
10199,[해파랑길] 45코스,레포츠,강원특별자치도,속초시,128.608558,38.163207,24902

In [ ]:
df_tv = pd.read_json('./data/무장애.json', encoding='utf-8')

In [72]:
df_tv

,addr1,addr2,areacode,cat1,cat2,cat3,contentid,contenttypeid,createdtime,firstimage,...,modifiedtime,sigungucode,tel,title,zipcode,lDongRegnCd,lDongSignguCd,lclsSystm1,lclsSystm2,lclsSystm3
0,충청북도 청주시 흥덕구 가경동,1438,33,A04,A0401,A04010200,1433504,38,20111111014944,http://tong.visitkorea.or.kr/cms/resource/50/3...,...,20250521105928,10,,가경 터미널시장,28398,43,113,SH,SH06,SH060200
1,전라남도 진도군 고군면 신비의바닷길 47,(고군면),38,A01,A0101,A01011200,126273,12,20031107090000,http://tong.visitkorea.or.kr/cms/resource/36/3...,...,20250808090412,21,,가계해수욕장,58911,46,900,NA,NA02,NA020900
2,서울특별시 종로구 평창30길 28 (평창동),,,,,,129854,14,20071106103314,https://tong.visitkorea.or.kr/cms/resource/11/...,...,20260311100340,,,가나아트센터,03004,11,110,VE,VE07,VE070600
3,경기도 양주시 장흥면 권율로 117,,31,A02,A0202,A02020600,129194,12,20060807090000,http://tong.visitkorea.or.kr/cms/resource/83/3...,...,20251030173026,18,,가나아트파크,11520,41,630,VE,VE02,VE020100
4,경기도 여주시 가남읍 대명산길 98,,31,A02,A0202,A02020700,2777865,12,20211123182854,http://tong.visitkorea.or.kr/cms/resource/71/2...,...,20250731161057,20,,가남체육공원,12662,41,670,VE,VE03,VE030500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10013,전북특별자치도 군산시 구영7길 133-4,(영화동),,,,,2580459,39,20181220001132,,...,20260227153825,,,[착한가게] 미주옥,54021,52,130,FD,FD01,FD010100
10014,강원특별자치도 강릉시 주문진읍 향호리,,32,A03,A0302,A03022700,2702497,28,20211230224128,http://tong.visitkorea.or.kr/cms/resource/35/2...,...,20250711101906,1,,[해파랑길] 41코스,25405,51,150,LS,LS01,LS011900
10015,강원특별자치도 양양군 현남면 인구리,,32,A03,A0302,A03022700,2710789,28,20210324180820,http://tong.visitkorea.or.kr/cms/resource/51/2...,...,20250711102626,7,,[해파랑길] 42코스,25053,51,830,LS,LS01,LS011900
10016,강원특별자치도 양양군 손양면 수산리,,32,A03,A0302,A03022700,2710791,28,20210324180947,http://tong.visitkorea.or.kr/cms/resource/61/2...,...,20250711100045,7,051-607-6395(해파랑길 종합 안내소)<br /> \n033-670-2207...,[해파랑길] 43코스,25042,51,830,LS,LS01,LS011900
10017,강원특별자치도 강릉시 강동면 헌화로 990-1,(정동진리),32,A02,A0206,A02060100,3544745,14,20250926115344,,...,20251023143000,1,,㈜타임트레인,25631,51,150,VE,VE07,VE070100

In [73]:
# 1. 삭제할 컬럼 리스트 정의
cols_to_drop = [
    'addr2', 'areacode', 'cat1', 'cat2', 'cat3', 'contentid', 
 'createdtime', 'firstimage', 'tel', 
    'showflag', 'lDongRegnCd', 'lDongSignguCd', 
    'lclsSystm1', 'lclsSystm2', 'lclsSystm3', 'firstimage2', 'cpyrhtDivCd', 'mlevel', 'modifiedtime', 'sigungucode' 
]

# 2. 컬럼 삭제 실행
df_tv2 = df_tv.drop(columns=cols_to_drop, errors='ignore')

In [78]:
df_tv2

,addr1,contenttypeid,mapx,mapy,title,zipcode
0,충청북도 청주시 흥덕구 가경동,38,127.434117,36.628649,가경 터미널시장,28398
1,전라남도 진도군 고군면 신비의바닷길 47,12,126.354741,34.435459,가계해수욕장,58911
2,서울특별시 종로구 평창30길 28 (평창동),14,126.975129,37.612290,가나아트센터,03004
3,경기도 양주시 장흥면 권율로 117,12,126.949164,37.725013,가나아트파크,11520
4,경기도 여주시 가남읍 대명산길 98,12,127.534914,37.201709,가남체육공원,12662
...,...,...,...,...,...,...
10013,전북특별자치도 군산시 구영7길 133-4,39,126.712268,35.989344,[착한가게] 미주옥,54021
10014,강원특별자치도 강릉시 주문진읍 향호리,28,128.818527,37.910854,[해파랑길] 41코스,25405
10015,강원특별자치도 양양군 현남면 인구리,28,128.759528,37.972954,[해파랑길] 42코스,25053
10016,강원특별자치도 양양군 손양면 수산리,28,128.674527,38.077254,[해파랑길] 43코스,25042
10017,강원특별자치도 강릉시 강동면 헌화로 990-1,14,129.037423,37.688268,㈜타임트레인,25631

In [79]:
# 1. 분리 로직 함수 정의
def split_korea_addr(addr):
    if not addr or pd.isna(addr):
        return "미분류", "미분류"
    
    parts = str(addr).split()
    
    sido = parts[0] if len(parts) > 0 else "미분류"
    
    sgg = parts[1] if len(parts) > 1 else ""
    
    return sido, sgg

# 2. 새로운 컬럼 생성 (sido_nm, sgg_nm)
df_tv2[['sido_nm', 'sgg_nm']] = df_tv2['addr1'].apply(
    lambda x: pd.Series(split_korea_addr(x))
)

# 3. 컬럼 순서 재배치 및 불필요 컬럼 삭제.
final_cols = ['title', 'sido_nm', 'sgg_nm', 'mapx', 'mapy', 'zipcode', 'contenttypeid']
df_tv2 = df_tv2[final_cols]

In [80]:
df_tv2

,title,sido_nm,sgg_nm,mapx,mapy,zipcode,contenttypeid
0,가경 터미널시장,충청북도,청주시,127.434117,36.628649,28398,38
1,가계해수욕장,전라남도,진도군,126.354741,34.435459,58911,12
2,가나아트센터,서울특별시,종로구,126.975129,37.612290,03004,14
3,가나아트파크,경기도,양주시,126.949164,37.725013,11520,12
4,가남체육공원,경기도,여주시,127.534914,37.201709,12662,12
...,...,...,...,...,...,...,...
10013,[착한가게] 미주옥,전북특별자치도,군산시,126.712268,35.989344,54021,39
10014,[해파랑길] 41코스,강원특별자치도,강릉시,128.818527,37.910854,25405,28
10015,[해파랑길] 42코스,강원특별자치도,양양군,128.759528,37.972954,25053,28
10016,[해파랑길] 43코스,강원특별자치도,양양군,128.674527,38.077254,25042,28
10017,㈜타임트레인,강원특별자치도,강릉시,129.037423,37.688268,25631,14

In [81]:
# 1. 변환용 딕셔너리 생성
content_type_map = {
    '12': '관광지',
    '14': '문화시설',
    '15': '축제공연행사',
    '28': '레포츠',
    '32': '숙박',
    '38': '쇼핑',
    '39': '음식점'
}

# 2. 데이터 타입 맞추기 
df_tv2['contenttypeid'] = df_tv2['contenttypeid'].astype(str)

df_tv2['content_type_nm'] = df_tv2['contenttypeid'].map(content_type_map).fillna('기타')

if 'content_type_nm' in df_tv2.columns:
    df_tv2 = df_tv2.drop(columns=['contenttypeid'], errors='ignore')
    
    cols = ['title', 'content_type_nm', 'sido_nm', 'sgg_nm'] + [c for c in df_tv2.columns if c not in ['title', 'content_type_nm', 'sido_nm', 'sgg_nm']]
    df_tv2 = df_tv2[cols]

C:\Users\playdata2\AppData\Local\Temp\ipykernel_9412\3902239570.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tv2['contenttypeid'] = df_tv2['contenttypeid'].astype(str)

In [84]:
# '항공사/여행사'가 아닌 데이터만 추출하여 저장
df_tour = df_tour[df_tour['mcate_nm'] != '항공사/여행사']

print(" '항공사/여행사' 데이터 삭제 완료!")

 '항공사/여행사' 데이터 삭제 완료!

In [85]:
df_tour

           poi_nm  mcate_nm  sido_nm sgg_nm           x          y
0          덕수궁중명전  유명사적/유적지    서울특별시     중구  126.972512  37.566707
1          마애여래좌상        국보     경상북도    봉화군  128.736928  36.931296
2          추월산관광지     일반관광지     전라남도    담양군  126.997724  35.401730
4      산머루농원오토캠핑장       캠핑장      경기도    파주시  126.960906  37.958494
5             해신당     천연기념물     경상북도    울진군  129.370689  37.127636
...           ...       ...      ...    ...         ...        ...
53881        용소폭포     폭포/계곡  강원특별자치도    영월군  128.570155  37.185208
53882    삼척대이리굴피집  유명사적/유적지  강원특별자치도    삼척시  129.014415  37.323768
53883     백전리물레방아     천연기념물  강원특별자치도    정선군  128.898136  37.246240
53884        곡운구곡     폭포/계곡  강원특별자치도    화천군  127.539121  38.053222
53885      펀치볼전적비   비/탑/문/각  강원특별자치도    양구군  128.045385  38.215918

[26471 rows x 6 columns]

In [20]:
print(df_tour['mcate_nm'].value_counts())

mcate_nm
항공사/여행사         26001
캠핑장              5103
일반관광지            3445
유명사적/유적지         2889
지역축제             2581
팜스테이             1444
먹거리/패션거리         1406
비/탑/문/각          1117
관광농원/허브마을        1017
폭포/계곡             957
관광안내소/매표소         938
야영장               903
서원/향교/서당          859
고택/생가/민속마을        707
휴양림/수목원           584
해수욕장              551
N                 462
일반유원지/일반놀이공원      436
보물                414
정보화마을             373
유명관광지             305
테마공원/대형놀이공원       293
성/성터              223
천연기념물             213
드라마/영화촬영지         204
왕릉/고분             128
식물원               117
국보                 69
동물원                46
영어마을               31
아쿠아리움/대형수족관        31
궁궐/종묘              13
온천지역               12
캠핑홀리데이(캠핑)          5
잼핑홀리데이(캠핑)          5
글램핑코리아(캠핑)          4
Name: count, dtype: int64

In [82]:
# 'N'가 아닌 데이터만 추출하여 저장
df_tour = df_tour[df_tour['mcate_nm'] != 'N']
df_tour = df_tour[df_tour['mcate_nm'] != '관광안내소/매표소']
df_tour = df_tour[df_tour['mcate_nm'] != '캠핑홀리데이(캠핑)']
df_tour = df_tour[df_tour['mcate_nm'] != '잼핑홀리데이(캠핑)']
df_tour = df_tour[df_tour['mcate_nm'] != '글램핑코리아(캠핑)']

In [83]:
print(df_tour['mcate_nm'].value_counts())

mcate_nm
항공사/여행사         26001
캠핑장              5103
일반관광지            3445
유명사적/유적지         2889
지역축제             2581
팜스테이             1444
먹거리/패션거리         1406
비/탑/문/각          1117
관광농원/허브마을        1017
폭포/계곡             957
야영장               903
서원/향교/서당          859
고택/생가/민속마을        707
휴양림/수목원           584
해수욕장              551
일반유원지/일반놀이공원      436
보물                414
정보화마을             373
유명관광지             305
테마공원/대형놀이공원       293
성/성터              223
천연기념물             213
드라마/영화촬영지         204
왕릉/고분             128
식물원               117
국보                 69
동물원                46
영어마을               31
아쿠아리움/대형수족관        31
궁궐/종묘              13
온천지역               12
Name: count, dtype: int64

In [23]:
df_tour

           poi_nm  mcate_nm  sido_nm sgg_nm           x          y
0          덕수궁중명전  유명사적/유적지    서울특별시     중구  126.972512  37.566707
1          마애여래좌상        국보     경상북도    봉화군  128.736928  36.931296
2          추월산관광지     일반관광지     전라남도    담양군  126.997724  35.401730
3           선우이엔지   항공사/여행사      경기도    광주시  127.291678  37.395739
4      산머루농원오토캠핑장       캠핑장      경기도    파주시  126.960906  37.958494
...           ...       ...      ...    ...         ...        ...
53881        용소폭포     폭포/계곡  강원특별자치도    영월군  128.570155  37.185208
53882    삼척대이리굴피집  유명사적/유적지  강원특별자치도    삼척시  129.014415  37.323768
53883     백전리물레방아     천연기념물  강원특별자치도    정선군  128.898136  37.246240
53884        곡운구곡     폭포/계곡  강원특별자치도    화천군  127.539121  38.053222
53885      펀치볼전적비   비/탑/문/각  강원특별자치도    양구군  128.045385  38.215918

[53886 rows x 6 columns]

In [86]:
import pandas as pd

# 1. 7가지 표준 카테고리에 맞춘 매핑 딕셔너리
category_mapping = {
    # 12: 관광지 
    '일반관광지': '관광지', '유명관광지': '관광지', '유명사적/유적지': '관광지', 
    '비/탑/문/각': '관광지', '서원/향교/서당': '관광지', '고택/생가/민속마을': '관광지', 
    '보물': '관광지', '성/성터': '관광지', '천연기념물': '관광지', '왕릉/고분': '관광지', 
    '국보': '관광지', '궁궐/종묘': '관광지', '폭포/계곡': '관광지', '해수욕장': '관광지', 
    '휴양림/수목원': '관광지', '식물원': '관광지', '드라마/영화촬영지': '관광지', 
    '관광안내소/매표소': '관광지', '온천지역': '관광지',  '팜스테이': '관광지', '관광농원/허브마을': '관광지', '정보화마을': '관광지', '영어마을': '관광지',
    
    # 14: 문화시설 
    '동물원': '문화시설', '식물원': '문화시설', '아쿠아리움/대형수족관': '문화시설',
    
    # 15: 축제공연행사
    '지역축제': '축제공연행사',
    
    # 28: 레포츠
    '캠핑장': '레포츠', '야영장': '레포츠', '일반유원지/일반놀이공원': '레포츠', 
    '테마공원/대형놀이공원': '레포츠',
    
    # 38: 쇼핑
    '먹거리/패션거리': '쇼핑'
    
    # 39: 음식점
}

# 2. 데이터프레임에 적용 (새 컬럼: tour_category)
df_tour['tour_category'] = df_tour['mcate_nm'].map(category_mapping)

# 3. 매핑되지 않은 항목 처리
df_tour['tour_category'] = df_tour['tour_category'].fillna('관광지') # 기본값은 관광지로 설정
print(" 7대 표준 카테고리 변환 완료!")
print(df_tour['tour_category'].value_counts())

 7대 표준 카테고리 변환 완료!
tour_category
관광지       15555
레포츠        6735
축제공연행사     2581
쇼핑         1406
문화시설        194
Name: count, dtype: int64

In [25]:
df_tour = df_tour.drop(columns=['mcate_nm'], errors='ignore')
print(" mcate_nm 컬럼 삭제 완료!")
print(f"현재 남은 컬럼 목록: {df_tour.columns.tolist()}")

 mcate_nm 컬럼 삭제 완료!
현재 남은 컬럼 목록: ['poi_nm', 'sido_nm', 'sgg_nm', 'x', 'y', 'tour_category']

In [87]:
# 1. 컬럼명 변경 매핑 (기존 이름 : 새 이름)
column_mapping = {
    'poi_nm': 'title',
    'tour_category': 'content_type_nm',
    'sido_nm': 'sido_nm',  
    'sgg_nm': 'sgg_nm',   
    'x': 'mapx',
    'y': 'mapy'
}

# 2. 이름 변경
df_tour = df_tour.rename(columns=column_mapping)

# 3. 컬럼 재배치
final_columns = ['title', 'content_type_nm', 'sido_nm', 'sgg_nm', 'mapx', 'mapy']
existing_final_cols = [c for c in final_columns if c in df_tour.columns]
df_tour = df_tour[existing_final_cols]

In [88]:
df_tour

            title content_type_nm  sido_nm sgg_nm        mapx       mapy
0          덕수궁중명전             관광지    서울특별시     중구  126.972512  37.566707
1          마애여래좌상             관광지     경상북도    봉화군  128.736928  36.931296
2          추월산관광지             관광지     전라남도    담양군  126.997724  35.401730
4      산머루농원오토캠핑장             레포츠      경기도    파주시  126.960906  37.958494
5             해신당             관광지     경상북도    울진군  129.370689  37.127636
...           ...             ...      ...    ...         ...        ...
53881        용소폭포             관광지  강원특별자치도    영월군  128.570155  37.185208
53882    삼척대이리굴피집             관광지  강원특별자치도    삼척시  129.014415  37.323768
53883     백전리물레방아             관광지  강원특별자치도    정선군  128.898136  37.246240
53884        곡운구곡             관광지  강원특별자치도    화천군  127.539121  38.053222
53885      펀치볼전적비             관광지  강원특별자치도    양구군  128.045385  38.215918

[26471 rows x 6 columns]

In [89]:
pet_df['zipcode'] = pd.to_numeric(pet_df['zipcode'], errors='coerce').astype('Int64')
df_tv2['zipcode'] = pd.to_numeric(df_tv2['zipcode'], errors='coerce').astype('Int64')

In [90]:
pet_df.rename(columns={'mapx': 'longitude', 'mapy': 'latitude'}, inplace=True)
df_tv2.rename(columns={'mapx': 'longitude', 'mapy': 'latitude'}, inplace=True)
df_tour.rename(columns={'mapx': 'longitude', 'mapy': 'latitude'}, inplace=True)

In [ ]:
df_tv2.to_pickle("barrier_free.pkl")
pet_df.to_pickle("pet_df_final.pkl")
df_tour.to_pickle("./tourpoi.pkl")