In [1]:
import pandas as pd

In [ ]:
tour_df = pd.read_excel("./data/2024년 국민여행조사 국내여행 RAWDATA.sav")

In [6]:
for col in tour_df.columns:
    print(col)

아이디
공통]  A_여행 횟수-1. 국내 관광/휴양 여행
공통]  A_여행 횟수-2. 국내 가족/친지/친구 방문 여행 - 관광/휴양 활동 포함
공통]  A_여행 횟수-3. 국내 단순 가족/친지/친구 방문 - 관광/휴양 활동이 포함되지 않음
공통]  A_여행 횟수-4. 국내 출장/업무 여행 - 관광/휴양 활동 포함
공통]  A_여행 횟수-5. 국내 단순 출장/업무 경험 - 관광/휴양 활동이 포함되지 않음
공통]  A-1_여행경험_국내 가족/친지/친구 방문 여행-관광/휴양 활동
공통]  A-2_여행경험_국내 가족/친지/친구 방문 여행-관광/휴양 활동 포함
공통]  A-3_여행경험_국내 단순 가족/친지/친구 방문-관광/휴양 활동 포함되지 않음
공통]  A-4_여행경험_국내 출장/업무 여행-관광/휴양 활동 포함
공통]  A-5_여행경험_국내 단순 출장/업무 경험-관광/휴양 활동 포함되지 않음
국내]  B_여행1차_본설문진행여부
국내]  B_여행1차_여행유형
국내]  B_여행1차_시작날짜_년
국내]  B_여행1차_시작날짜_월
국내]  B_여행1차_시작날짜_일
국내]  B_여행1차_끝날짜_년
국내]  B_여행1차_끝날짜_월
국내]  B_여행1차_끝날짜_일
국내]  B_여행1차_여행일수(박)
국내]  B_여행1차_여행 총경비
국내]  B_여행1차_지출비용에 포함되는 인원수
국내]  B_여행1차_1인지출비용
국내]  B_여행1차_평일이 포함된 경우 휴가/방학 여부
국내]  B_여행1차_주요 이동 교통 수단(지역간)
국내]  B_여행1차_주요 이동 교통 수단(지역간).1
국내]  B_여행1차_주요 이동 교통 수단(지역간).2
국내]  B_여행1차_주요 이동 교통 수단(지역내)
국내]  B_여행1차_주요 이동 교통 수단(지역내).1
국내]  B_여행1차_주요 이동 교통 수단(지역내).2
국내]  B_여행1차_1번째방문지_여행시작일_년
국내]  B_여행1차_1번째방문지_여행시작일_월
국내]  B_여행1차_1번째방문지_여행시작일_일
국내]  B_여행1차_1번째방문지_여행종료일_년
국내]  B_여행1차_1번째방문지_여행종료일_월
국내]  B_여행1차_1번째방문지_여행종료일_일
국내]  B_여행1차_1번째방문지_방문 지역
국내]  B_여행1차_1번째방문지_숙박 지역
국내]  B_여행1차_1번째방문지_숙박 시설
국내]  B_여행1차_2번째방문지_여행시작일_년
국내]  B_여행1차_2번째방문지_여행시작일_월
국내]  B_여행1차_2번째방문지_여행시작일_일
국내]  B_여행1차_2번째방문지_여행종료일_년
국내]  B_여행1차_2번째방문지_여행종료일_월
국내]  B_여행1차_2번째방문지_여행종료일_일
국내]  B_여행1차_2번째방문지_방문 지역
국내]  B_여행1차_2번째방문지_숙박 지역
국내]  B_여행1차_2번째방문지_숙박 시설
국내]  B_여행1차_3번째방문지_여행시작일_년
국내]  B_여행1차_3번째방문지_여행시작일_월
국내]  B_여행1차_3번째방문지_여행시작일_일
국내]  B_여행1차_3번째방문지_여행종료일_년
국내]  B_여행1차_3번째방문지_여행종료일_월
국내]  B_여행1차_3번째방문지_여행종료일_일
국내]  B_여행1차_3번째방문지_방문 지역
국내]  B_여행1차_3번째방문지_숙박 지역
국내]  B_여행1차_3번째방문지_숙박 시설
국내]  B_여행1차_4번째방문지_여행시작일_년
국내]  B_여행1차_4번째방문지_여행시작일_월
국내]  B_여행1차_4번째방문지_여행시작일_일
국내]  B_여행1차_4번째방문지_여행종료일_년
국내]  B_여행1차_4번째방문지_여행종료일_월
국내]  B_여행1차_4번째방문지_여행종료일_일
국내]  B_여행1차_4번째방문지_방문 지역
국내]  B_여행1차_4번째방문지_숙박 지역
국내]  B_여행1차_4번째방문지_숙박 시설
국내]  B_여행1차_5번째방문지_여행시작일_년
국내]  B_여행1차_5번째방문지_여행시작일_월
국내]  B_여행1차_5번째방문지_여행시작일_일
국내]  B_여행1차_5번째방문지_여행종료일_년
국내]  B_여행1차_5번째방문지_여행종료일_월
국내]  B_여행1차_5번째방문지_여행종료일_일
국내]  B_여행1차_5번째방문지_방문 지역
국내]  B_여행1차_5번째방문지_숙박 지역
국내]  B_여행1차_5번째방문지_숙박 시설
국내]  B_여행1차_6번째방문지_여행시작일_년
국내]  B_여행1차_6번째방문지_여행시작일_월
국내]  B_여행1차_6번째방문지_여행시작일_일
국내]  B_여행1차_6번째방문지_여행종료일_년
국내]  B_여행1차_6번째방문지_여행종료일_월
국내]  B_여행1차_6번째방문지_여행종료일_일
국내]  B_여행1차_6번째방문지_방문 지역
국내]  B_여행1차_6번째방문지_숙박 지역
국내]  B_여행1차_6번째방문지_숙박 시설
국내]  B_여행1차_7번째방문지_여행시작일_년
국내]  B_여행1차_7번째방문지_여행시작일_월
국내]  B_여행1차_7번째방문지_여행시작일_일
국내]  B_여행1차_7번째방문지_여행종료일_년
국내]  B_여행1차_7번째방문지_여행종료일_월
국내]  B_여행1차_7번째방문지_여행종료일_일
국내]  B_여행1차_7번째방문지_방문 지역
국내]  B_여행1차_7번째방문지_숙박 지역
국내]  B_여행1차_7번째방문지_숙박 시설
국내]  B_여행1차_8번째방문지_여행시작일_년
국내]  B_여행1차_8번째방문지_여행시작일_월
국내]  B_여행1차_8번째방문지_여행시작일_일
국내]  B_여행1차_8번째방문지_여행종료일_년
국내]  B_여행1차_8번째방문지_여행종료일_월
국내]  B_여행1차_8번째방문지_여행종료일_일
국내]  B_여행1차_8번째방문지_방문 지역
국내]  B_여행1차_8번째방문지_숙박 지역
국내]  B_여행1차_8번째방문지_숙박 시설
국내]  B_여행1차_9번째방문지_여행시작일_년
국내]  B_여행1차_9번째방문지_여행시작일_월
국내]  B_여행1차_9번째방문지_여행시작일_일
국내]  B_여행1차_9번째방문지_여행종료일_년
국내]  B_여행1차_9번째방문지_여행종료일_월
국내]  B_여행1차_9번째방문지_여행종료일_일
국내]  B_여행1차_9번째방문지_방문 지역
국내]  B_여행1차_9번째방문지_숙박 지역
국내]  B_여행1차_9번째방문지_숙박 시설
국내]  B_여행1차_10번째방문지_여행시작일_년
국내]  B_여행1차_10번째방문지_여행시작일_월
국내]  B_여행1차_10번째방문지_여행시작일_일
국내]  B_여행1차_10번째방문지_여행종료일_년
국내]  B_여행1차_10번째방문지_여행종료일_월
국내]  B_여행1차_10번째방문지_여행종료일_일
국내]  B_여행1차_10번째방문지_방문 지역
국내]  B_여행1차_10번째방문지_숙박 지역
국내]  B_여행1차_10번째방문지_숙박 시설
국내]  B_여행1차_11번째방문지_여행시작일_년
국내]  B_여행1차_11번째방문지_여행시작일_월
국내]  B_여행1차_11번째방문지_여행시작일_일
국내]  B_여행1차_11번째방문지_여행종료일_년
국내]  B_여행1차_11번째방문지_여행종료일_월
국내]  B_여행1차_11번째방문지_여행종료일_일
국내]  B_여행1차_11번째방문지_방문 지역
국내]  B_여행1차_11번째방문지_숙박 지역
국내]  B_여행1차_11번째방문지_숙박 시설
국내]  B_여행1차_12번째방문지_여행시작일_년
국내]  B_여행1차_12번째방문지_여행시작일_월
국내]  B_여행1차_12번째방문지_여행시작일_일
국내]  B_여행1차_12번째방문지_여행종료일_년
국내]  B_여행1차_12번째방문지_여행종료일_월
국내]  B_여행1차_12번째방문지_여행종료일_일
국내]  B_여행1차_12번째방문지_방문 지역
국내]  B_여행1차_12번째방문지_숙박 지역
국내]  B_여행1차_12번째방문지_숙박 시설
국내]  B_여행1차_13번째방문지_여행시작일_년
국내]  B_여행1차_13번째방문지_여행시작일_월
국내]  B_여행1차_13번째방문지_여행시작일_일
국내]  B_여행1차_13번째방문지_여행종료일_년
국내]  B_여행1차_13번째방문지_여행종료일_월
국내]  B_여행1차_13번째방문지_여행종료일_일
국내]  B_여행1차_13번째방문지_방문 지역
국내]  B_여행1차_13번째방문지_숙박 지역
국내]  B_여행1차_13번째방문지_숙박 시설
국내]  B_여행1차_14번째방문지_여행시작일_년
국내]  B_여행1차_14번째방문지_여행시작일_월
국내]  B_여행1차_14번째방문지_여행시작일_일
국내]  B_여행1차_14번째방문지_여행종료일_년
국내]  B_여행1차_14번째방문지_여행종료일_월
국내]  B_여행1차_14번째방문지_여행종료일_일
국내]  B_여행1차_14번째방문지_방문 지역
국내]  B_여행1차_14번째방문지_숙박 지역
국내]  B_여행1차_14번째방문지_숙박 시설
국내]  B_여행1차_15번째방문지_여행시작일_년
국내]  B_여행1차_15번째방문지_여행시작일_월
국내]  B_여행1차_15번째방문지_여행시작일_일
국내]  B_여행1차_15번째방문지_여행종료일_년
국내]  B_여행1차_15번째방문지_여행종료일_월
국내]  B_여행1차_15번째방문지_여행종료일_일
국내]  B_여행1차_15번째방문지_방문 지역
국내]  B_여행1차_15번째방문지_숙박 지역
국내]  B_여행1차_15번째방문지_숙박 시설
국내]  B_여행1차_16번째방문지_여행시작일_년
국내]  B_여행1차_16번째방문지_여행시작일_월
국내]  B_여행1차_16번째방문지_여행시작일_일
국내]  B_여행1차_16번째방문지_여행종료일_년
국내]  B_여행1차_16번째방문지_여행종료일_월
국내]  B_여행1차_16번째방문지_여행종료일_일
국내]  B_여행1차_16번째방문지_방문 지역
국내]  B_여행1차_16번째방문지_숙박 지역
국내]  B_여행1차_16번째방문지_숙박 시설
국내]  B_여행1차_17번째방문지_여행시작일_년
국내]  B_여행1차_17번째방문지_여행시작일_월
국내]  B_여행1차_17번째방문지_여행시작일_일
국내]  B_여행1차_17번째방문지_여행종료일_년
국내]  B_여행1차_17번째방문지_여행종료일_월
국내]  B_여행1차_17번째방문지_여행종료일_일
국내]  B_여행1차_17번째방문지_방문 지역
국내]  B_여행1차_17번째방문지_숙박 지역
국내]  B_여행1차_17번째방문지_숙박 시설
국내]  B_여행2차_본설문진행여부
국내]  B_여행2차_여행유형
국내]  B_여행2차_시작날짜_년
국내]  B_여행2차_시작날짜_월
국내]  B_여행2차_시작날짜_일
국내]  B_여행2차_끝날짜_년
국내]  B_여행2차_끝날짜_월
국내]  B_여행2차_끝날짜_일
국내]  B_여행2차_여행일수(박)
국내]  B_여행2차_여행 총경비
국내]  B_여행2차_지출비용에 포함되는 인원수
국내]  B_여행2차_1인지출비용
국내]  B_여행2차_평일이 포함된 경우 휴가/방학 여부
국내]  B_여행2차_주요 이동 교통 수단(지역간)
국내]  B_여행2차_주요 이동 교통 수단(지역간).1
국내]  B_여행2차_주요 이동 교통 수단(지역간).2
국내]  B_여행2차_주요 이동 교통 수단(지역내)
국내]  B_여행2차_주요 이동 교통 수단(지역내).1
국내]  B_여행2차_주요 이동 교통 수단(지역내).2
국내]  B_여행2차_1번째방문지_여행시작일_년
국내]  B_여행2차_1번째방문지_여행시작일_월
국내]  B_여행2차_1번째방문지_여행시작일_일
국내]  B_여행2차_1번째방문지_여행종료일_년
국내]  B_여행2차_1번째방문지_여행종료일_월
국내]  B_여행2차_1번째방문지_여행종료일_일
국내]  B_여행2차_1번째방문지_방문 지역
국내]  B_여행2차_1번째방문지_숙박 지역
국내]  B_여행2차_1번째방문지_숙박 시설
국내]  B_여행2차_2번째방문지_여행시작일_년
국내]  B_여행2차_2번째방문지_여행시작일_월
국내]  B_여행2차_2번째방문지_여행시작일_일
국내]  B_여행2차_2번째방문지_여행종료일_년
국내]  B_여행2차_2번째방문지_여행종료일_월
국내]  B_여행2차_2번째방문지_여행종료일_일
국내]  B_여행2차_2번째방문지_방문 지역
국내]  B_여행2차_2번째방문지_숙박 지역
국내]  B_여행2차_2번째방문지_숙박 시설
국내]  B_여행2차_3번째방문지_여행시작일_년
국내]  B_여행2차_3번째방문지_여행시작일_월
국내]  B_여행2차_3번째방문지_여행시작일_일
국내]  B_여행2차_3번째방문지_여행종료일_년
국내]  B_여행2차_3번째방문지_여행종료일_월
국내]  B_여행2차_3번째방문지_여행종료일_일
국내]  B_여행2차_3번째방문지_방문 지역
국내]  B_여행2차_3번째방문지_숙박 지역
국내]  B_여행2차_3번째방문지_숙박 시설
국내]  B_여행2차_4번째방문지_여행시작일_년
국내]  B_여행2차_4번째방문지_여행시작일_월
국내]  B_여행2차_4번째방문지_여행시작일_일
국내]  B_여행2차_4번째방문지_여행종료일_년
국내]  B_여행2차_4번째방문지_여행종료일_월
국내]  B_여행2차_4번째방문지_여행종료일_일
국내]  B_여행2차_4번째방문지_방문 지역
국내]  B_여행2차_4번째방문지_숙박 지역
국내]  B_여행2차_4번째방문지_숙박 시설
국내]  B_여행2차_5번째방문지_여행시작일_년
국내]  B_여행2차_5번째방문지_여행시작일_월
국내]  B_여행2차_5번째방문지_여행시작일_일
국내]  B_여행2차_5번째방문지_여행종료일_년
국내]  B_여행2차_5번째방문지_여행종료일_월
국내]  B_여행2차_5번째방문지_여행종료일_일
국내]  B_여행2차_5번째방문지_방문 지역
국내]  B_여행2차_5번째방문지_숙박 지역
국내]  B_여행2차_5번째방문지_숙박 시설
국내]  B_여행2차_6번째방문지_여행시작일_년
국내]  B_여행2차_6번째방문지_여행시작일_월
국내]  B_여행2차_6번째방문지_여행시작일_일
국내]  B_여행2차_6번째방문지_여행종료일_년
국내]  B_여행2차_6번째방문지_여행종료일_월
국내]  B_여행2차_6번째방문지_여행종료일_일
국내]  B_여행2차_6번째방문지_방문 지역
국내]  B_여행2차_6번째방문지_숙박 지역
국내]  B_여행2차_6번째방문지_숙박 시설
국내]  B_여행2차_7번째방문지_여행시작일_년
국내]  B_여행2차_7번째방문지_여행시작일_월
국내]  B_여행2차_7번째방문지_여행시작일_일
국내]  B_여행2차_7번째방문지_여행종료일_년
국내]  B_여행2차_7번째방문지_여행종료일_월
국내]  B_여행2차_7번째방문지_여행종료일_일
국내]  B_여행2차_7번째방문지_방문 지역
국내]  B_여행2차_7번째방문지_숙박 지역
국내]  B_여행2차_7번째방문지_숙박 시설
국내]  B_여행2차_8번째방문지_여행시작일_년
국내]  B_여행2차_8번째방문지_여행시작일_월
국내]  B_여행2차_8번째방문지_여행시작일_일
국내]  B_여행2차_8번째방문지_여행종료일_년
국내]  B_여행2차_8번째방문지_여행종료일_월
국내]  B_여행2차_8번째방문지_여행종료일_일
국내]  B_여행2차_8번째방문지_방문 지역
국내]  B_여행2차_8번째방문지_숙박 지역
국내]  B_여행2차_8번째방문지_숙박 시설
국내]  B_여행2차_9번째방문지_여행시작일_년
국내]  B_여행2차_9번째방문지_여행시작일_월
국내]  B_여행2차_9번째방문지_여행시작일_일
국내]  B_여행2차_9번째방문지_여행종료일_년
국내]  B_여행2차_9번째방문지_여행종료일_월
국내]  B_여행2차_9번째방문지_여행종료일_일
국내]  B_여행2차_9번째방문지_방문 지역
국내]  B_여행2차_9번째방문지_숙박 지역
국내]  B_여행2차_9번째방문지_숙박 시설
국내]  B_여행2차_10번째방문지_여행시작일_년
국내]  B_여행2차_10번째방문지_여행시작일_월
국내]  B_여행2차_10번째방문지_여행시작일_일
국내]  B_여행2차_10번째방문지_여행종료일_년
국내]  B_여행2차_10번째방문지_여행종료일_월
국내]  B_여행2차_10번째방문지_여행종료일_일
국내]  B_여행2차_10번째방문지_방문 지역
국내]  B_여행2차_10번째방문지_숙박 지역
국내]  B_여행2차_10번째방문지_숙박 시설
국내]  B_여행2차_11번째방문지_여행시작일_년
국내]  B_여행2차_11번째방문지_여행시작일_월
국내]  B_여행2차_11번째방문지_여행시작일_일
국내]  B_여행2차_11번째방문지_여행종료일_년
국내]  B_여행2차_11번째방문지_여행종료일_월
국내]  B_여행2차_11번째방문지_여행종료일_일
국내]  B_여행2차_11번째방문지_방문 지역
국내]  B_여행2차_11번째방문지_숙박 지역
국내]  B_여행2차_11번째방문지_숙박 시설
국내]  B_여행2차_12번째방문지_여행시작일_년
국내]  B_여행2차_12번째방문지_여행시작일_월
국내]  B_여행2차_12번째방문지_여행시작일_일
국내]  B_여행2차_12번째방문지_여행종료일_년
국내]  B_여행2차_12번째방문지_여행종료일_월
국내]  B_여행2차_12번째방문지_여행종료일_일
국내]  B_여행2차_12번째방문지_방문 지역
국내]  B_여행2차_12번째방문지_숙박 지역
국내]  B_여행2차_12번째방문지_숙박 시설
국내]  B_여행2차_13번째방문지_여행시작일_년
국내]  B_여행2차_13번째방문지_여행시작일_월
국내]  B_여행2차_13번째방문지_여행시작일_일
국내]  B_여행2차_13번째방문지_여행종료일_년
국내]  B_여행2차_13번째방문지_여행종료일_월
국내]  B_여행2차_13번째방문지_여행종료일_일
국내]  B_여행2차_13번째방문지_방문 지역
국내]  B_여행2차_13번째방문지_숙박 지역
국내]  B_여행2차_13번째방문지_숙박 시설
국내]  B_여행2차_14번째방문지_여행시작일_년
국내]  B_여행2차_14번째방문지_여행시작일_월
국내]  B_여행2차_14번째방문지_여행시작일_일
국내]  B_여행2차_14번째방문지_여행종료일_년
국내]  B_여행2차_14번째방문지_여행종료일_월
국내]  B_여행2차_14번째방문지_여행종료일_일
국내]  B_여행2차_14번째방문지_방문 지역
국내]  B_여행2차_14번째방문지_숙박 지역
국내]  B_여행2차_14번째방문지_숙박 시설
국내]  B_여행2차_15번째방문지_여행시작일_년
국내]  B_여행2차_15번째방문지_여행시작일_월
국내]  B_여행2차_15번째방문지_여행시작일_일
국내]  B_여행2차_15번째방문지_여행종료일_년
국내]  B_여행2차_15번째방문지_여행종료일_월
국내]  B_여행2차_15번째방문지_여행종료일_일
국내]  B_여행2차_15번째방문지_방문 지역
국내]  B_여행2차_15번째방문지_숙박 지역
국내]  B_여행2차_15번째방문지_숙박 시설
국내]  B_여행2차_16번째방문지_여행시작일_년
국내]  B_여행2차_16번째방문지_여행시작일_월
국내]  B_여행2차_16번째방문지_여행시작일_일
국내]  B_여행2차_16번째방문지_여행종료일_년
국내]  B_여행2차_16번째방문지_여행종료일_월
국내]  B_여행2차_16번째방문지_여행종료일_일
국내]  B_여행2차_16번째방문지_방문 지역
국내]  B_여행2차_16번째방문지_숙박 지역
국내]  B_여행2차_16번째방문지_숙박 시설
국내]  B_여행2차_17번째방문지_여행시작일_년
국내]  B_여행2차_17번째방문지_여행시작일_월
국내]  B_여행2차_17번째방문지_여행시작일_일
국내]  B_여행2차_17번째방문지_여행종료일_년
국내]  B_여행2차_17번째방문지_여행종료일_월
국내]  B_여행2차_17번째방문지_여행종료일_일
국내]  B_여행2차_17번째방문지_방문 지역
국내]  B_여행2차_17번째방문지_숙박 지역
국내]  B_여행2차_17번째방문지_숙박 시설
국내]  B_여행3차_본설문진행여부
국내]  B_여행3차_여행유형
국내]  B_여행3차_시작날짜_년
국내]  B_여행3차_시작날짜_월
국내]  B_여행3차_시작날짜_일
국내]  B_여행3차_끝날짜_년
국내]  B_여행3차_끝날짜_월
국내]  B_여행3차_끝날짜_일
국내]  B_여행3차_여행일수(박)
국내]  B_여행3차_여행 총경비
국내]  B_여행3차_지출비용에 포함되는 인원수
국내]  B_여행3차_1인지출비용
국내]  B_여행3차_평일이 포함된 경우 휴가/방학 여부
국내]  B_여행3차_주요 이동 교통 수단(지역간)
국내]  B_여행3차_주요 이동 교통 수단(지역간).1
국내]  B_여행3차_주요 이동 교통 수단(지역간).2
국내]  B_여행3차_주요 이동 교통 수단(지역내)
국내]  B_여행3차_주요 이동 교통 수단(지역내).1
국내]  B_여행3차_주요 이동 교통 수단(지역내).2
국내]  B_여행3차_1번째방문지_여행시작일_년
국내]  B_여행3차_1번째방문지_여행시작일_월
국내]  B_여행3차_1번째방문지_여행시작일_일
국내]  B_여행3차_1번째방문지_여행종료일_년
국내]  B_여행3차_1번째방문지_여행종료일_월
국내]  B_여행3차_1번째방문지_여행종료일_일
국내]  B_여행3차_1번째방문지_방문 지역
국내]  B_여행3차_1번째방문지_숙박 지역
국내]  B_여행3차_1번째방문지_숙박 시설
국내]  B_여행3차_2번째방문지_여행시작일_년
국내]  B_여행3차_2번째방문지_여행시작일_월
국내]  B_여행3차_2번째방문지_여행시작일_일
국내]  B_여행3차_2번째방문지_여행종료일_년
국내]  B_여행3차_2번째방문지_여행종료일_월
국내]  B_여행3차_2번째방문지_여행종료일_일
국내]  B_여행3차_2번째방문지_방문 지역
국내]  B_여행3차_2번째방문지_숙박 지역
국내]  B_여행3차_2번째방문지_숙박 시설
국내]  B_여행3차_3번째방문지_여행시작일_년
국내]  B_여행3차_3번째방문지_여행시작일_월
국내]  B_여행3차_3번째방문지_여행시작일_일
국내]  B_여행3차_3번째방문지_여행종료일_년
국내]  B_여행3차_3번째방문지_여행종료일_월
국내]  B_여행3차_3번째방문지_여행종료일_일
국내]  B_여행3차_3번째방문지_방문 지역
국내]  B_여행3차_3번째방문지_숙박 지역
국내]  B_여행3차_3번째방문지_숙박 시설
국내]  B_여행3차_4번째방문지_여행시작일_년
국내]  B_여행3차_4번째방문지_여행시작일_월
국내]  B_여행3차_4번째방문지_여행시작일_일
국내]  B_여행3차_4번째방문지_여행종료일_년
국내]  B_여행3차_4번째방문지_여행종료일_월
국내]  B_여행3차_4번째방문지_여행종료일_일
국내]  B_여행3차_4번째방문지_방문 지역
국내]  B_여행3차_4번째방문지_숙박 지역
국내]  B_여행3차_4번째방문지_숙박 시설
국내]  B_여행3차_5번째방문지_여행시작일_년
국내]  B_여행3차_5번째방문지_여행시작일_월
국내]  B_여행3차_5번째방문지_여행시작일_일
국내]  B_여행3차_5번째방문지_여행종료일_년
국내]  B_여행3차_5번째방문지_여행종료일_월
국내]  B_여행3차_5번째방문지_여행종료일_일
국내]  B_여행3차_5번째방문지_방문 지역
국내]  B_여행3차_5번째방문지_숙박 지역
국내]  B_여행3차_5번째방문지_숙박 시설
국내]  B_여행3차_6번째방문지_여행시작일_년
국내]  B_여행3차_6번째방문지_여행시작일_월
국내]  B_여행3차_6번째방문지_여행시작일_일
국내]  B_여행3차_6번째방문지_여행종료일_년
국내]  B_여행3차_6번째방문지_여행종료일_월
국내]  B_여행3차_6번째방문지_여행종료일_일
국내]  B_여행3차_6번째방문지_방문 지역
국내]  B_여행3차_6번째방문지_숙박 지역
국내]  B_여행3차_6번째방문지_숙박 시설
국내]  B_여행3차_7번째방문지_여행시작일_년
국내]  B_여행3차_7번째방문지_여행시작일_월
국내]  B_여행3차_7번째방문지_여행시작일_일
국내]  B_여행3차_7번째방문지_여행종료일_년
국내]  B_여행3차_7번째방문지_여행종료일_월
국내]  B_여행3차_7번째방문지_여행종료일_일
국내]  B_여행3차_7번째방문지_방문 지역
국내]  B_여행3차_7번째방문지_숙박 지역
국내]  B_여행3차_7번째방문지_숙박 시설
국내]  B_여행3차_8번째방문지_여행시작일_년
국내]  B_여행3차_8번째방문지_여행시작일_월
국내]  B_여행3차_8번째방문지_여행시작일_일
국내]  B_여행3차_8번째방문지_여행종료일_년
국내]  B_여행3차_8번째방문지_여행종료일_월
국내]  B_여행3차_8번째방문지_여행종료일_일
국내]  B_여행3차_8번째방문지_방문 지역
국내]  B_여행3차_8번째방문지_숙박 지역
국내]  B_여행3차_8번째방문지_숙박 시설
국내]  B_여행3차_9번째방문지_여행시작일_년
국내]  B_여행3차_9번째방문지_여행시작일_월
국내]  B_여행3차_9번째방문지_여행시작일_일
국내]  B_여행3차_9번째방문지_여행종료일_년
국내]  B_여행3차_9번째방문지_여행종료일_월
국내]  B_여행3차_9번째방문지_여행종료일_일
국내]  B_여행3차_9번째방문지_방문 지역
국내]  B_여행3차_9번째방문지_숙박 지역
국내]  B_여행3차_9번째방문지_숙박 시설
국내]  B_여행3차_10번째방문지_여행시작일_년
국내]  B_여행3차_10번째방문지_여행시작일_월
국내]  B_여행3차_10번째방문지_여행시작일_일
국내]  B_여행3차_10번째방문지_여행종료일_년
국내]  B_여행3차_10번째방문지_여행종료일_월
국내]  B_여행3차_10번째방문지_여행종료일_일
국내]  B_여행3차_10번째방문지_방문 지역
국내]  B_여행3차_10번째방문지_숙박 지역
국내]  B_여행3차_10번째방문지_숙박 시설
국내]  B_여행3차_11번째방문지_여행시작일_년
국내]  B_여행3차_11번째방문지_여행시작일_월
국내]  B_여행3차_11번째방문지_여행시작일_일
국내]  B_여행3차_11번째방문지_여행종료일_년
국내]  B_여행3차_11번째방문지_여행종료일_월
국내]  B_여행3차_11번째방문지_여행종료일_일
국내]  B_여행3차_11번째방문지_방문 지역
국내]  B_여행3차_11번째방문지_숙박 지역
국내]  B_여행3차_11번째방문지_숙박 시설
국내]  B_여행3차_12번째방문지_여행시작일_년
국내]  B_여행3차_12번째방문지_여행시작일_월
국내]  B_여행3차_12번째방문지_여행시작일_일
국내]  B_여행3차_12번째방문지_여행종료일_년
국내]  B_여행3차_12번째방문지_여행종료일_월
국내]  B_여행3차_12번째방문지_여행종료일_일
국내]  B_여행3차_12번째방문지_방문 지역
국내]  B_여행3차_12번째방문지_숙박 지역
국내]  B_여행3차_12번째방문지_숙박 시설
국내]  B_여행3차_13번째방문지_여행시작일_년
국내]  B_여행3차_13번째방문지_여행시작일_월
국내]  B_여행3차_13번째방문지_여행시작일_일
국내]  B_여행3차_13번째방문지_여행종료일_년
국내]  B_여행3차_13번째방문지_여행종료일_월
국내]  B_여행3차_13번째방문지_여행종료일_일
국내]  B_여행3차_13번째방문지_방문 지역
국내]  B_여행3차_13번째방문지_숙박 지역
국내]  B_여행3차_13번째방문지_숙박 시설
국내]  B_여행3차_14번째방문지_여행시작일_년
국내]  B_여행3차_14번째방문지_여행시작일_월
국내]  B_여행3차_14번째방문지_여행시작일_일
국내]  B_여행3차_14번째방문지_여행종료일_년
국내]  B_여행3차_14번째방문지_여행종료일_월
국내]  B_여행3차_14번째방문지_여행종료일_일
국내]  B_여행3차_14번째방문지_방문 지역
국내]  B_여행3차_14번째방문지_숙박 지역
국내]  B_여행3차_14번째방문지_숙박 시설
국내]  B_여행3차_15번째방문지_여행시작일_년
국내]  B_여행3차_15번째방문지_여행시작일_월
국내]  B_여행3차_15번째방문지_여행시작일_일
국내]  B_여행3차_15번째방문지_여행종료일_년
국내]  B_여행3차_15번째방문지_여행종료일_월
국내]  B_여행3차_15번째방문지_여행종료일_일
국내]  B_여행3차_15번째방문지_방문 지역
국내]  B_여행3차_15번째방문지_숙박 지역
국내]  B_여행3차_15번째방문지_숙박 시설
국내]  B_여행3차_16번째방문지_여행시작일_년
국내]  B_여행3차_16번째방문지_여행시작일_월
국내]  B_여행3차_16번째방문지_여행시작일_일
국내]  B_여행3차_16번째방문지_여행종료일_년
국내]  B_여행3차_16번째방문지_여행종료일_월
국내]  B_여행3차_16번째방문지_여행종료일_일
국내]  B_여행3차_16번째방문지_방문 지역
국내]  B_여행3차_16번째방문지_숙박 지역
국내]  B_여행3차_16번째방문지_숙박 시설
국내]  B_여행3차_17번째방문지_여행시작일_년
국내]  B_여행3차_17번째방문지_여행시작일_월
국내]  B_여행3차_17번째방문지_여행시작일_일
국내]  B_여행3차_17번째방문지_여행종료일_년
국내]  B_여행3차_17번째방문지_여행종료일_월
국내]  B_여행3차_17번째방문지_여행종료일_일
국내]  B_여행3차_17번째방문지_방문 지역
국내]  B_여행3차_17번째방문지_숙박 지역
국내]  B_여행3차_17번째방문지_숙박 시설
국내]  B_여행4차_본설문진행여부
국내]  B_여행4차_여행유형
국내]  B_여행4차_시작날짜_년
국내]  B_여행4차_시작날짜_월
국내]  B_여행4차_시작날짜_일
국내]  B_여행4차_끝날짜_년
국내]  B_여행4차_끝날짜_월
국내]  B_여행4차_끝날짜_일
국내]  B_여행4차_여행일수(박)
국내]  B_여행4차_여행 총경비
국내]  B_여행4차_지출비용에 포함되는 인원수
국내]  B_여행4차_1인지출비용
국내]  B_여행4차_평일이 포함된 경우 휴가/방학 여부
국내]  B_여행4차_주요 이동 교통 수단(지역간)
국내]  B_여행4차_주요 이동 교통 수단(지역간).1
국내]  B_여행4차_주요 이동 교통 수단(지역간).2
국내]  B_여행4차_주요 이동 교통 수단(지역내)
국내]  B_여행4차_주요 이동 교통 수단(지역내).1
국내]  B_여행4차_주요 이동 교통 수단(지역내).2
국내]  B_여행4차_1번째방문지_여행시작일_년
국내]  B_여행4차_1번째방문지_여행시작일_월
국내]  B_여행4차_1번째방문지_여행시작일_일
국내]  B_여행4차_1번째방문지_여행종료일_년
국내]  B_여행4차_1번째방문지_여행종료일_월
국내]  B_여행4차_1번째방문지_여행종료일_일
국내]  B_여행4차_1번째방문지_방문 지역
국내]  B_여행4차_1번째방문지_숙박 지역
국내]  B_여행4차_1번째방문지_숙박 시설
국내]  B_여행4차_2번째방문지_여행시작일_년
국내]  B_여행4차_2번째방문지_여행시작일_월
국내]  B_여행4차_2번째방문지_여행시작일_일
국내]  B_여행4차_2번째방문지_여행종료일_년
국내]  B_여행4차_2번째방문지_여행종료일_월
국내]  B_여행4차_2번째방문지_여행종료일_일
국내]  B_여행4차_2번째방문지_방문 지역
국내]  B_여행4차_2번째방문지_숙박 지역
국내]  B_여행4차_2번째방문지_숙박 시설
국내]  B_여행4차_3번째방문지_여행시작일_년
국내]  B_여행4차_3번째방문지_여행시작일_월
국내]  B_여행4차_3번째방문지_여행시작일_일
국내]  B_여행4차_3번째방문지_여행종료일_년
국내]  B_여행4차_3번째방문지_여행종료일_월
국내]  B_여행4차_3번째방문지_여행종료일_일
국내]  B_여행4차_3번째방문지_방문 지역
국내]  B_여행4차_3번째방문지_숙박 지역
국내]  B_여행4차_3번째방문지_숙박 시설
국내]  B_여행4차_4번째방문지_여행시작일_년
국내]  B_여행4차_4번째방문지_여행시작일_월
국내]  B_여행4차_4번째방문지_여행시작일_일
국내]  B_여행4차_4번째방문지_여행종료일_년
국내]  B_여행4차_4번째방문지_여행종료일_월
국내]  B_여행4차_4번째방문지_여행종료일_일
국내]  B_여행4차_4번째방문지_방문 지역
국내]  B_여행4차_4번째방문지_숙박 지역
국내]  B_여행4차_4번째방문지_숙박 시설
국내]  B_여행4차_5번째방문지_여행시작일_년
국내]  B_여행4차_5번째방문지_여행시작일_월
국내]  B_여행4차_5번째방문지_여행시작일_일
국내]  B_여행4차_5번째방문지_여행종료일_년
국내]  B_여행4차_5번째방문지_여행종료일_월
국내]  B_여행4차_5번째방문지_여행종료일_일
국내]  B_여행4차_5번째방문지_방문 지역
국내]  B_여행4차_5번째방문지_숙박 지역
국내]  B_여행4차_5번째방문지_숙박 시설
국내]  B_여행4차_6번째방문지_여행시작일_년
국내]  B_여행4차_6번째방문지_여행시작일_월
국내]  B_여행4차_6번째방문지_여행시작일_일
국내]  B_여행4차_6번째방문지_여행종료일_년
국내]  B_여행4차_6번째방문지_여행종료일_월
국내]  B_여행4차_6번째방문지_여행종료일_일
국내]  B_여행4차_6번째방문지_방문 지역
국내]  B_여행4차_6번째방문지_숙박 지역
국내]  B_여행4차_6번째방문지_숙박 시설
국내]  B_여행4차_7번째방문지_여행시작일_년
국내]  B_여행4차_7번째방문지_여행시작일_월
국내]  B_여행4차_7번째방문지_여행시작일_일
국내]  B_여행4차_7번째방문지_여행종료일_년
국내]  B_여행4차_7번째방문지_여행종료일_월
국내]  B_여행4차_7번째방문지_여행종료일_일
국내]  B_여행4차_7번째방문지_방문 지역
국내]  B_여행4차_7번째방문지_숙박 지역
국내]  B_여행4차_7번째방문지_숙박 시설
국내]  B_여행4차_8번째방문지_여행시작일_년
국내]  B_여행4차_8번째방문지_여행시작일_월
국내]  B_여행4차_8번째방문지_여행시작일_일
국내]  B_여행4차_8번째방문지_여행종료일_년
국내]  B_여행4차_8번째방문지_여행종료일_월
국내]  B_여행4차_8번째방문지_여행종료일_일
국내]  B_여행4차_8번째방문지_방문 지역
국내]  B_여행4차_8번째방문지_숙박 지역
국내]  B_여행4차_8번째방문지_숙박 시설
국내]  B_여행4차_9번째방문지_여행시작일_년
국내]  B_여행4차_9번째방문지_여행시작일_월
국내]  B_여행4차_9번째방문지_여행시작일_일
국내]  B_여행4차_9번째방문지_여행종료일_년
국내]  B_여행4차_9번째방문지_여행종료일_월
국내]  B_여행4차_9번째방문지_여행종료일_일
국내]  B_여행4차_9번째방문지_방문 지역
국내]  B_여행4차_9번째방문지_숙박 지역
국내]  B_여행4차_9번째방문지_숙박 시설
국내]  B_여행4차_10번째방문지_여행시작일_년
국내]  B_여행4차_10번째방문지_여행시작일_월
국내]  B_여행4차_10번째방문지_여행시작일_일
국내]  B_여행4차_10번째방문지_여행종료일_년
국내]  B_여행4차_10번째방문지_여행종료일_월
국내]  B_여행4차_10번째방문지_여행종료일_일
국내]  B_여행4차_10번째방문지_방문 지역
국내]  B_여행4차_10번째방문지_숙박 지역
국내]  B_여행4차_10번째방문지_숙박 시설
국내]  B_여행4차_11번째방문지_여행시작일_년
국내]  B_여행4차_11번째방문지_여행시작일_월
국내]  B_여행4차_11번째방문지_여행시작일_일
국내]  B_여행4차_11번째방문지_여행종료일_년
국내]  B_여행4차_11번째방문지_여행종료일_월
국내]  B_여행4차_11번째방문지_여행종료일_일
국내]  B_여행4차_11번째방문지_방문 지역
국내]  B_여행4차_11번째방문지_숙박 지역
국내]  B_여행4차_11번째방문지_숙박 시설
국내]  B_여행4차_12번째방문지_여행시작일_년
국내]  B_여행4차_12번째방문지_여행시작일_월
국내]  B_여행4차_12번째방문지_여행시작일_일
국내]  B_여행4차_12번째방문지_여행종료일_년
국내]  B_여행4차_12번째방문지_여행종료일_월
국내]  B_여행4차_12번째방문지_여행종료일_일
국내]  B_여행4차_12번째방문지_방문 지역
국내]  B_여행4차_12번째방문지_숙박 지역
국내]  B_여행4차_12번째방문지_숙박 시설
국내]  B_여행4차_13번째방문지_여행시작일_년
국내]  B_여행4차_13번째방문지_여행시작일_월
국내]  B_여행4차_13번째방문지_여행시작일_일
국내]  B_여행4차_13번째방문지_여행종료일_년
국내]  B_여행4차_13번째방문지_여행종료일_월
국내]  B_여행4차_13번째방문지_여행종료일_일
국내]  B_여행4차_13번째방문지_방문 지역
국내]  B_여행4차_13번째방문지_숙박 지역
국내]  B_여행4차_13번째방문지_숙박 시설
국내]  B_여행4차_14번째방문지_여행시작일_년
국내]  B_여행4차_14번째방문지_여행시작일_월
국내]  B_여행4차_14번째방문지_여행시작일_일
국내]  B_여행4차_14번째방문지_여행종료일_년
국내]  B_여행4차_14번째방문지_여행종료일_월
국내]  B_여행4차_14번째방문지_여행종료일_일
국내]  B_여행4차_14번째방문지_방문 지역
국내]  B_여행4차_14번째방문지_숙박 지역
국내]  B_여행4차_14번째방문지_숙박 시설
국내]  B_여행4차_15번째방문지_여행시작일_년
국내]  B_여행4차_15번째방문지_여행시작일_월
국내]  B_여행4차_15번째방문지_여행시작일_일
국내]  B_여행4차_15번째방문지_여행종료일_년
국내]  B_여행4차_15번째방문지_여행종료일_월
국내]  B_여행4차_15번째방문지_여행종료일_일
국내]  B_여행4차_15번째방문지_방문 지역
국내]  B_여행4차_15번째방문지_숙박 지역
국내]  B_여행4차_15번째방문지_숙박 시설
국내]  B_여행4차_16번째방문지_여행시작일_년
국내]  B_여행4차_16번째방문지_여행시작일_월
국내]  B_여행4차_16번째방문지_여행시작일_일
국내]  B_여행4차_16번째방문지_여행종료일_년
국내]  B_여행4차_16번째방문지_여행종료일_월
국내]  B_여행4차_16번째방문지_여행종료일_일
국내]  B_여행4차_16번째방문지_방문 지역
국내]  B_여행4차_16번째방문지_숙박 지역
국내]  B_여행4차_16번째방문지_숙박 시설
국내]  B_여행4차_17번째방문지_여행시작일_년
국내]  B_여행4차_17번째방문지_여행시작일_월
국내]  B_여행4차_17번째방문지_여행시작일_일
국내]  B_여행4차_17번째방문지_여행종료일_년
국내]  B_여행4차_17번째방문지_여행종료일_월
국내]  B_여행4차_17번째방문지_여행종료일_일
국내]  B_여행4차_17번째방문지_방문 지역
국내]  B_여행4차_17번째방문지_숙박 지역
국내]  B_여행4차_17번째방문지_숙박 시설
국내]  B_여행5차_본설문진행여부
국내]  B_여행5차_여행유형
국내]  B_여행5차_시작날짜_년
국내]  B_여행5차_시작날짜_월
국내]  B_여행5차_시작날짜_일
국내]  B_여행5차_끝날짜_년
국내]  B_여행5차_끝날짜_월
국내]  B_여행5차_끝날짜_일
국내]  B_여행5차_여행일수(박)
국내]  B_여행5차_여행 총경비
국내]  B_여행5차_지출비용에 포함되는 인원수
국내]  B_여행5차_1인지출비용
국내]  B_여행5차_평일이 포함된 경우 휴가/방학 여부
국내]  B_여행5차_주요 이동 교통 수단(지역간)
국내]  B_여행5차_주요 이동 교통 수단(지역간).1
국내]  B_여행5차_주요 이동 교통 수단(지역간).2
국내]  B_여행5차_주요 이동 교통 수단(지역내)
국내]  B_여행5차_주요 이동 교통 수단(지역내).1
국내]  B_여행5차_주요 이동 교통 수단(지역내).2
국내]  B_여행5차_1번째방문지_여행시작일_년
국내]  B_여행5차_1번째방문지_여행시작일_월
국내]  B_여행5차_1번째방문지_여행시작일_일
국내]  B_여행5차_1번째방문지_여행종료일_년
국내]  B_여행5차_1번째방문지_여행종료일_월
국내]  B_여행5차_1번째방문지_여행종료일_일
국내]  B_여행5차_1번째방문지_방문 지역
국내]  B_여행5차_1번째방문지_숙박 지역
국내]  B_여행5차_1번째방문지_숙박 시설
국내]  B_여행5차_2번째방문지_여행시작일_년
국내]  B_여행5차_2번째방문지_여행시작일_월
국내]  B_여행5차_2번째방문지_여행시작일_일
국내]  B_여행5차_2번째방문지_여행종료일_년
국내]  B_여행5차_2번째방문지_여행종료일_월
국내]  B_여행5차_2번째방문지_여행종료일_일
국내]  B_여행5차_2번째방문지_방문 지역
국내]  B_여행5차_2번째방문지_숙박 지역
국내]  B_여행5차_2번째방문지_숙박 시설
국내]  B_여행5차_3번째방문지_여행시작일_년
국내]  B_여행5차_3번째방문지_여행시작일_월
국내]  B_여행5차_3번째방문지_여행시작일_일
국내]  B_여행5차_3번째방문지_여행종료일_년
국내]  B_여행5차_3번째방문지_여행종료일_월
국내]  B_여행5차_3번째방문지_여행종료일_일
국내]  B_여행5차_3번째방문지_방문 지역
국내]  B_여행5차_3번째방문지_숙박 지역
국내]  B_여행5차_3번째방문지_숙박 시설
국내]  B_여행5차_4번째방문지_여행시작일_년
국내]  B_여행5차_4번째방문지_여행시작일_월
국내]  B_여행5차_4번째방문지_여행시작일_일
국내]  B_여행5차_4번째방문지_여행종료일_년
국내]  B_여행5차_4번째방문지_여행종료일_월
국내]  B_여행5차_4번째방문지_여행종료일_일
국내]  B_여행5차_4번째방문지_방문 지역

In [22]:
tour_df

,아이디,공통] A_여행 횟수-1. 국내 관광/휴양 여행,공통] A_여행 횟수-2. 국내 가족/친지/친구 방문 여행 - 관광/휴양 활동 포함,공통] A_여행 횟수-3. 국내 단순 가족/친지/친구 방문 - 관광/휴양 활동이 포함되지 않음,공통] A_여행 횟수-4. 국내 출장/업무 여행 - 관광/휴양 활동 포함,공통] A_여행 횟수-5. 국내 단순 출장/업무 경험 - 관광/휴양 활동이 포함되지 않음,공통] A-1_여행경험_국내 가족/친지/친구 방문 여행-관광/휴양 활동,공통] A-2_여행경험_국내 가족/친지/친구 방문 여행-관광/휴양 활동 포함,공통] A-3_여행경험_국내 단순 가족/친지/친구 방문-관광/휴양 활동 포함되지 않음,공통] A-4_여행경험_국내 출장/업무 여행-관광/휴양 활동 포함,...,국내] 여행방문지_기타당일여행1,국내] 여행방문지_기타당일여행2,국내] 여행방문지_기타당일여행3,국내] 여행방문지_기타당일여행4,국내] 여행방문지_기타당일여행5,국내] 여행방문지_기타당일여행6,국내] 여행방문지_기타당일여행7,국내] 여행방문지_기타당일여행8,국내] 여행방문지_기타당일여행9,국내] 여행방문지_기타당일여행10
0,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,MON_EXP_1,MON_EXP_2,MON_EXP_3,MON_EXP_4,...,국내_여행방문지_기타당일1,국내_여행방문지_기타당일2,국내_여행방문지_기타당일3,국내_여행방문지_기타당일4,국내_여행방문지_기타당일5,국내_여행방문지_기타당일6,국내_여행방문지_기타당일7,국내_여행방문지_기타당일8,국내_여행방문지_기타당일9,국내_여행방문지_기타당일10
1,11010550271_275001,0,0,0,0,0,2,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010550271_275003,1,0,0,0,0,1,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010550271_275004,1,0,0,0,0,1,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010550271_275007,0,0,0,0,0,2,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51750,39020611051_690403,1,0,0,0,0,1,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51751,39020611051_690406,1,0,0,0,0,1,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51752,39020611051_690416,0,0,0,0,0,2,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51753,39020611051_690417,1,0,0,0,0,1,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51754,39020611051_690420,1,0,0,0,0,1,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

# 1. 고정 컬럼 (직접 매칭이 안 될 경우를 대비해 키워드로 찾기)
fixed_keywords = [
    "성별", "연령", "반려동물 동반 여부", 
    "전반적 만족도", "재방문 의향", "타인 추천 의향"
]
fixed_cols = [c for c in tour_df.columns if any(k in c for k in fixed_keywords)]

# 2. 반복 생성 컬럼 리스트 (키워드 기반 추출)
dynamic_cols = []

# Q6-2. 여행 동반자 유형 (1~12) & Q4. 여행지 활동 (1~21)
dynamic_cols += [c for c in tour_df.columns if "여행 동반자 유형_" in c or "여행지에서의 활동_" in c]

# 3. 여행차/방문지 관련 컬럼
# 'B_여행'과 '방문지'가 동시에 들어있고, '방문 지역/숙박 지역/숙박 시설'로 끝나는 것들 추출
visit_keywords = ["방문 지역", "숙박 지역", "숙박 시설"]
visit_cols = [c for c in tour_df.columns if "B_여행" in c and "방문지" in c and any(k in c for k in visit_keywords)]

# 4. 교통 수단 관련 컬럼
transport_keywords = ["주요 이동 교통 수단"]
transport_cols = [c for c in tour_df.columns if any(k in c for k in transport_keywords)]

# 5. 모든 컬럼 합치기
target_columns = list(dict.fromkeys(fixed_cols + dynamic_cols + visit_cols + transport_cols))

# 6. 최종 데이터프레임 생성
tour_df2 = tour_df[target_columns]

# 7. 결과 확인
print(f" 추출된 컬럼 예시 (방문지 관련): {visit_cols[:3]}")
print(f" 필터링 전 컬럼 수: {tour_df.shape[1]}")
print(f" 필터링 후 컬럼 수: {tour_df2.shape[1]}")

✅ 추출된 컬럼 예시 (방문지 관련): ['국내]  B_여행1차_1번째방문지_방문 지역', '국내]  B_여행1차_1번째방문지_숙박 지역', '국내]  B_여행1차_1번째방문지_숙박 시설']
✅ 필터링 전 컬럼 수: 2227
✅ 필터링 후 컬럼 수: 324

In [25]:
tour_df2

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,A.[국내] Q4. 여행지에서의 활동_1,A.[국내] Q4. 여행지에서의 활동_2,A.[국내] Q4. 여행지에서의 활동_3,A.[국내] Q4. 여행지에서의 활동_4,...,국내] B_여행4차_주요 이동 교통 수단(지역간).2,국내] B_여행4차_주요 이동 교통 수단(지역내),국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행4차_주요 이동 교통 수단(지역내).2,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역간).1,국내] B_여행5차_주요 이동 교통 수단(지역간).2,국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역내).2
0,A6C,A9,A10,A11,BSEX,BAGE,A4_1,A4_2,A4_3,A4_4,...,D_TRA4_B7A_3,D_TRA4_B7B_1,D_TRA4_B7B_2,D_TRA4_B7B_3,D_TRA5_B7A_1,D_TRA5_B7A_2,D_TRA5_B7A_3,D_TRA5_B7B_1,D_TRA5_B7B_2,D_TRA5_B7B_3
1,NaN,NaN,NaN,NaN,1,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,4,4,4,1,4,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,4,4,1,3,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51750,1,4,4,3,2,2,NaN,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51751,1,4,4,4,2,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51752,NaN,NaN,NaN,NaN,2,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51753,2,4,4,4,1,5,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51754,2,4,4,3,2,3,NaN,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
import numpy as np

# 1. 번호와 명칭 매핑 딕셔너리 생성
companion_map = {
    1: '배우자', 2: '자녀', 3: '손자/손녀', 4: '부모', 5: '조부모',
    6: '형제/자매', 7: '친구', 8: '연인', 9: '직장동료',
    10: '친목 단체/모임', 11: '학교 단체', 12: '기타'
}

# 2. 통합 대상 컬럼 리스트 추출 (Q6-2_1 ~ Q6-2_12)
companion_cols = [f"A.[국내] Q6-2. 여행 동반자 유형_{i}" for i in range(1, 13)]

def get_companion_type(row):
    for i, col in enumerate(companion_cols, 1):
        # 값이 1이거나, 결측치가 아니거나, 0보다 큰 경우
        if pd.notna(row[col]) and row[col] != 0:
            return companion_map.get(i, '기타')
    return '단독(없음)' # 모든 컬럼이 비어있을 경우

# 3. 새로운 통합 컬럼 생성
tour_df2['companion_type'] = tour_df2.apply(get_companion_type, axis=1)

# 4.기존의 분리된 12개 컬럼 삭제
tour_df2 = tour_df2.drop(columns=companion_cols)

C:\Users\playdata2\AppData\Local\Temp\ipykernel_6872\1570995487.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tour_df2['companion_type'] = tour_df2.apply(get_companion_type, axis=1)

In [27]:
tour_df2

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,A.[국내] Q4. 여행지에서의 활동_1,A.[국내] Q4. 여행지에서의 활동_2,A.[국내] Q4. 여행지에서의 활동_3,A.[국내] Q4. 여행지에서의 활동_4,...,국내] B_여행4차_주요 이동 교통 수단(지역내),국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행4차_주요 이동 교통 수단(지역내).2,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역간).1,국내] B_여행5차_주요 이동 교통 수단(지역간).2,국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역내).2,companion_type
0,A6C,A9,A10,A11,BSEX,BAGE,A4_1,A4_2,A4_3,A4_4,...,D_TRA4_B7B_1,D_TRA4_B7B_2,D_TRA4_B7B_3,D_TRA5_B7A_1,D_TRA5_B7A_2,D_TRA5_B7A_3,D_TRA5_B7B_1,D_TRA5_B7B_2,D_TRA5_B7B_3,배우자
1,NaN,NaN,NaN,NaN,1,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음)
2,1,4,4,4,1,4,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자
3,1,4,4,4,1,3,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자
4,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51750,1,4,4,3,2,2,NaN,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구
51751,1,4,4,4,2,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음)
51752,NaN,NaN,NaN,NaN,2,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음)
51753,2,4,4,4,1,5,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자
51754,2,4,4,3,2,3,NaN,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀

In [ ]:
import pandas as pd

# 1. 활동 번호와 명칭 매핑 딕셔너리
activity_map = {
    1: '자연 및 풍경감상', 2: '음식관광', 3: '야외 스포츠/레포츠', 
    4: '역사 유적지 방문', 5: '테마파크/동식물원', 6: '휴식/휴양', 
    7: '온천/스파', 8: '쇼핑', 9: '문화예술/전시 관람', 
    10: '스포츠 경기관람', 11: '지역 축제/이벤트', 12: '교육/체험 프로그램', 
    13: '종교/성지순례', 14: '카지노/경마 등', 15: '시티투어', 
    16: '드라마 촬영지 방문', 17: '유흥/오락', 18: '가족/친지 방문', 
    19: '회의참가/시찰', 20: '교육/훈련/연수', 21: '기타'
}

# 2. 통합 대상 컬럼 리스트 추출 (Q4_1 ~ Q4_21)
activity_cols = [f"A.[국내] Q4. 여행지에서의 활동_{i}" for i in range(1, 22)]

# 3. 통합 함수 정의 (모든 활동을 나열하는 방식)
def get_all_activities(row):
    selected = []
    for i, col in enumerate(activity_cols, 1):
        # 값이 1(체크됨)이거나 결측치가 아닌 경우
        if pd.notna(row[col]) and row[col] != 0:
            selected.append(activity_map.get(i))
    
    return ", ".join(selected) if selected else "활동 없음"

# 4. 새로운 통합 컬럼 생성 (travel_activity)
tour_df2['travel_activity'] = tour_df2.apply(get_all_activities, axis=1)

# 5.기존의 분리된 21개 컬럼 삭제
tour_df2 = tour_df2.drop(columns=activity_cols)

In [29]:
tour_df2

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,...,국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행4차_주요 이동 교통 수단(지역내).2,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역간).1,국내] B_여행5차_주요 이동 교통 수단(지역간).2,국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역내).2,companion_type,travel_activity
0,A6C,A9,A10,A11,BSEX,BAGE,D_TRA1_1_SPOT,D_TRA1_1_Q6_Ar,D_TRA1_1_Q6,D_TRA1_2_SPOT,...,D_TRA4_B7B_2,D_TRA4_B7B_3,D_TRA5_B7A_1,D_TRA5_B7A_2,D_TRA5_B7A_3,D_TRA5_B7B_1,D_TRA5_B7B_2,D_TRA5_B7B_3,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 역사 유적지 방문, 테마파크/동..."
1,NaN,NaN,NaN,NaN,1,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
2,1,4,4,4,1,4,32030,32030,4,32030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
3,1,4,4,4,1,3,32030,NaN,NaN,32030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
4,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51750,1,4,4,3,2,2,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
51751,1,4,4,4,2,3,31010,31010,12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
51752,NaN,NaN,NaN,NaN,2,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
51753,2,4,4,4,1,5,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
51754,2,4,4,3,2,3,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
import pandas as pd

# 1. 성별 매핑 딕셔너리
gender_map = {1: '남자', 2: '여자'}

# 2. 연령대 매핑 딕셔너리
age_map = {
    1: '15~19세',
    2: '20대',
    3: '30대',
    4: '40대',
    5: '50대',
    6: '60대',
    7: '70세 이상'
}

if "공통]  성별" in tour_df2.columns:
    tour_df2["공통]  성별"] = tour_df2["공통]  성별"].map(gender_map)

if "공통]  연령" in tour_df2.columns:
    tour_df2["공통]  연령"] = tour_df2["공통]  연령"].map(age_map)

In [31]:
tour_df2

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,...,국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행4차_주요 이동 교통 수단(지역내).2,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역간).1,국내] B_여행5차_주요 이동 교통 수단(지역간).2,국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역내).2,companion_type,travel_activity
0,A6C,A9,A10,A11,NaN,NaN,D_TRA1_1_SPOT,D_TRA1_1_Q6_Ar,D_TRA1_1_Q6,D_TRA1_2_SPOT,...,D_TRA4_B7B_2,D_TRA4_B7B_3,D_TRA5_B7A_1,D_TRA5_B7A_2,D_TRA5_B7A_3,D_TRA5_B7B_1,D_TRA5_B7B_2,D_TRA5_B7B_3,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 역사 유적지 방문, 테마파크/동..."
1,NaN,NaN,NaN,NaN,남자,50대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
2,1,4,4,4,남자,40대,32030,32030,4,32030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
3,1,4,4,4,남자,30대,32030,NaN,NaN,32030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
4,NaN,NaN,NaN,NaN,남자,40대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51750,1,4,4,3,여자,20대,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
51751,1,4,4,4,여자,30대,31010,31010,12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
51752,NaN,NaN,NaN,NaN,여자,60대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
51753,2,4,4,4,남자,50대,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
51754,2,4,4,3,여자,30대,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
tour_df3 = tour_df2.iloc[1:].copy()

tour_df3 = tour_df3.reset_index(drop=True)

In [33]:
tour_df3

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,...,국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행4차_주요 이동 교통 수단(지역내).2,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역간).1,국내] B_여행5차_주요 이동 교통 수단(지역간).2,국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역내).2,companion_type,travel_activity
0,NaN,NaN,NaN,NaN,남자,50대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
1,1,4,4,4,남자,40대,32030,32030,4,32030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
2,1,4,4,4,남자,30대,32030,NaN,NaN,32030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
3,NaN,NaN,NaN,NaN,남자,40대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
4,NaN,NaN,NaN,NaN,여자,20대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51749,1,4,4,3,여자,20대,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
51750,1,4,4,4,여자,30대,31010,31010,12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
51751,NaN,NaN,NaN,NaN,여자,60대,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),활동 없음
51752,2,4,4,4,남자,50대,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
51753,2,4,4,3,여자,30대,39010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
# 1. 특정 컬럼('방문 지역')이 결측치인 행 삭제
tour_df3 = tour_df3.dropna(subset=['국내]  B_여행1차_1번째방문지_방문 지역'])
tour_df3 = tour_df3.reset_index(drop=True)

In [ ]:
tour_df3

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,국내] B_여행1차_2번째방문지_숙박 지역,국내] B_여행1차_2번째방문지_숙박 시설,국내] B_여행1차_3번째방문지_방문 지역,국내] B_여행1차_3번째방문지_숙박 지역,국내] B_여행1차_3번째방문지_숙박 시설,국내] B_여행1차_4번째방문지_방문 지역,국내] B_여행1차_4번째방문지_숙박 지역,국내] B_여행1차_4번째방문지_숙박 시설,국내] B_여행1차_5번째방문지_방문 지역,국내] B_여행1차_5번째방문지_숙박 지역,국내] B_여행1차_5번째방문지_숙박 시설,국내] B_여행1차_6번째방문지_방문 지역,국내] B_여행1차_6번째방문지_숙박 지역,국내] B_여행1차_6번째방문지_숙박 시설,국내] B_여행1차_7번째방문지_방문 지역,국내] B_여행1차_7번째방문지_숙박 지역,국내] B_여행1차_7번째방문지_숙박 시설,국내] B_여행1차_8번째방문지_방문 지역,국내] B_여행1차_8번째방문지_숙박 지역,국내] B_여행1차_8번째방문지_숙박 시설,국내] B_여행1차_9번째방문지_방문 지역,국내] B_여행1차_9번째방문지_숙박 지역,국내] B_여행1차_9번째방문지_숙박 시설,국내] B_여행1차_10번째방문지_방문 지역,국내] B_여행1차_10번째방문지_숙박 지역,국내] B_여행1차_10번째방문지_숙박 시설,국내] B_여행1차_11번째방문지_방문 지역,국내] B_여행1차_11번째방문지_숙박 지역,국내] B_여행1차_11번째방문지_숙박 시설,국내] B_여행1차_12번째방문지_방문 지역,국내] B_여행1차_12번째방문지_숙박 지역,국내] B_여행1차_12번째방문지_숙박 시설,국내] B_여행1차_13번째방문지_방문 지역,국내] B_여행1차_13번째방문지_숙박 지역,국내] B_여행1차_13번째방문지_숙박 시설,국내] B_여행1차_14번째방문지_방문 지역,국내] B_여행1차_14번째방문지_숙박 지역,국내] B_여행1차_14번째방문지_숙박 시설,국내] B_여행1차_15번째방문지_방문 지역,국내] B_여행1차_15번째방문지_숙박 지역,국내] B_여행1차_15번째방문지_숙박 시설,국내] B_여행1차_16번째방문지_방문 지역,국내] B_여행1차_16번째방문지_숙박 지역,국내] B_여행1차_16번째방문지_숙박 시설,국내] B_여행1차_17번째방문지_방문 지역,국내] B_여행1차_17번째방문지_숙박 지역,국내] B_여행1차_17번째방문지_숙박 시설,국내] B_여행2차_1번째방문지_방문 지역,국내] B_여행2차_1번째방문지_숙박 지역,국내] B_여행2차_1번째방문지_숙박 시설,국내] B_여행2차_2번째방문지_방문 지역,국내] B_여행2차_2번째방문지_숙박 지역,국내] B_여행2차_2번째방문지_숙박 시설,국내] B_여행2차_3번째방문지_방문 지역,국내] B_여행2차_3번째방문지_숙박 지역,국내] B_여행2차_3번째방문지_숙박 시설,국내] B_여행2차_4번째방문지_방문 지역,국내] B_여행2차_4번째방문지_숙박 지역,국내] B_여행2차_4번째방문지_숙박 시설,국내] B_여행2차_5번째방문지_방문 지역,국내] B_여행2차_5번째방문지_숙박 지역,국내] B_여행2차_5번째방문지_숙박 시설,국내] B_여행2차_6번째방문지_방문 지역,국내] B_여행2차_6번째방문지_숙박 지역,국내] B_여행2차_6번째방문지_숙박 시설,국내] B_여행2차_7번째방문지_방문 지역,국내] B_여행2차_7번째방문지_숙박 지역,국내] B_여행2차_7번째방문지_숙박 시설,국내] B_여행2차_8번째방문지_방문 지역,국내] B_여행2차_8번째방문지_숙박 지역,국내] B_여행2차_8번째방문지_숙박 시설,국내] B_여행2차_9번째방문지_방문 지역,국내] B_여행2차_9번째방문지_숙박 지역,국내] B_여행2차_9번째방문지_숙박 시설,국내] B_여행2차_10번째방문지_방문 지역,국내] B_여행2차_10번째방문지_숙박 지역,국내] B_여행2차_10번째방문지_숙박 시설,국내] B_여행2차_11번째방문지_방문 지역,국내] B_여행2차_11번째방문지_숙박 지역,국내] B_여행2차_11번째방문지_숙박 시설,국내] B_여행2차_12번째방문지_방문 지역,국내] B_여행2차_12번째방문지_숙박 지역,국내] B_여행2차_12번째방문지_숙박 시설,국내] B_여행2차_13번째방문지_방문 지역,국내] B_여행2차_13번째방문지_숙박 지역,국내] B_여행2차_13번째방문지_숙박 시설,국내] B_여행2차_14번째방문지_방문 지역,국내] B_여행2차_14번째방문지_숙박 지역,국내] B_여행2차_14번째방문지_숙박 시설,국내] B_여행2차_15번째방문지_방문 지역,국내] B_여행2차_15번째방문지_숙박 지역,국내] B_여행2차_15번째방문지_숙박 시설,국내] B_여행2차_16번째방문지_방문 지역,국내] B_여행2차_16번째방문지_숙박 지역,국내] B_여행2차_16번째방문지_숙박 시설,국내] B_여행2차_17번째방문지_방문 지역,국내] B_여행2차_17번째방문지_숙박 지역,국내] B_여행2차_17번째방문지_숙박 시설,국내] B_여행3차_1번째방문지_방문 지역,국내] B_여행3차_1번째방문지_숙박 지역,국내] B_여행3차_1번째방문지_숙박 시설,국내] B_여행3차_2번째방문지_방문 지역,국내] B_여행3차_2번째방문지_숙박 지역,국내] B_여행3차_2번째방문지_숙박 시설,국내] B_여행3차_3번째방문지_방문 지역,국내] B_여행3차_3번째방문지_숙박 지역,국내] B_여행3차_3번째방문지_숙박 시설,국내] B_여행3차_4번째방문지_방문 지역,국내] B_여행3차_4번째방문지_숙박 지역,국내] B_여행3차_4번째방문지_숙박 시설,국내] B_여행3차_5번째방문지_방문 지역,국내] B_여행3차_5번째방문지_숙박 지역,국내] B_여행3차_5번째방문지_숙박 시설,국내] B_여행3차_6번째방문지_방문 지역,국내] B_여행3차_6번째방문지_숙박 지역,국내] B_여행3차_6번째방문지_숙박 시설,국내] B_여행3차_7번째방문지_방문 지역,국내] B_여행3차_7번째방문지_숙박 지역,국내] B_여행3차_7번째방문지_숙박 시설,국내] B_여행3차_8번째방문지_방문 지역,국내] B_여행3차_8번째방문지_숙박 지역,국내] B_여행3차_8번째방문지_숙박 시설,국내] B_여행3차_9번째방문지_방문 지역,국내] B_여행3차_9번째방문지_숙박 지역,국내] B_여행3차_9번째방문지_숙박 시설,국내] B_여행3차_10번째방문지_방문 지역,국내] B_여행3차_10번째방문지_숙박 지역,국내] B_여행3차_10번째방문지_숙박 시설,국내] B_여행3차_11번째방문지_방문 지역,국내] B_여행3차_11번째방문지_숙박 지역,국내] B_여행3차_11번째방문지_숙박 시설,국내] B_여행3차_12번째방문지_방문 지역,국내] B_여행3차_12번째방문지_숙박 지역,국내] B_여행3차_12번째방문지_숙박 시설,국내] B_여행3차_13번째방문지_방문 지역,국내] B_여행3차_13번째방문지_숙박 지역,국내] B_여행3차_13번째방문지_숙박 시설,국내] B_여행3차_14번째방문지_방문 지역,국내] B_여행3차_14번째방문지_숙박 지역,국내] B_여행3차_14번째방문지_숙박 시설,국내] B_여행3차_15번째방문지_방문 지역,국내] B_여행3차_15번째방문지_숙박 지역,국내] B_여행3차_15번째방문지_숙박 시설,국내] B_여행3차_16번째방문지_방문 지역,국내] B_여행3차_16번째방문지_숙박 지역,국내] B_여행3차_16번째방문지_숙박 시설,국내] B_여행3차_17번째방문지_방문 지역,국내] B_여행3차_17번째방문지_숙박 지역,국내] B_여행3차_17번째방문지_숙박 시설,국내] B_여행4차_1번째방문지_방문 지역,국내] B_여행4차_1번째방문지_숙박 지역,국내] B_여행4차_1번째방문지_숙박 시설,국내] B_여행4차_2번째방문지_방문 지역,국내] B_여행4차_2번째방문지_숙박 지역,국내] B_여행4차_2번째방문지_숙박 시설,국내] B_여행4차_3번째방문지_방문 지역,국내] B_여행4차_3번째방문지_숙박 지역,국내] B_여행4차_3번째방문지_숙박 시설,국내] B_여행4차_4번째방문지_방문 지역,국내] B_여행4차_4번째방문지_숙박 지역,국내] B_여행4차_4번째방문지_숙박 시설,국내] B_여행4차_5번째방문지_방문 지역,국내] B_여행4차_5번째방문지_숙박 지역,국내] B_여행4차_5번째방문지_숙박 시설,국내] B_여행4차_6번째방문지_방문 지역,국내] B_여행4차_6번째방문지_숙박 지역,국내] B_여행4차_6번째방문지_숙박 시설,국내] B_여행4차_7번째방문지_방문 지역,국내] B_여행4차_7번째방문지_숙박 지역,국내] B_여행4차_7번째방문지_숙박 시설,국내] B_여행4차_8번째방문지_방문 지역,국내] B_여행4차_8번째방문지_숙박 지역,국내] B_여행4차_8번째방문지_숙박 시설,국내] B_여행4차_9번째방문지_방문 지역,국내] B_여행4차_9번째방문지_숙박 지역,국내] B_여행4차_9번째방문지_숙박 시설,국내] B_여행4차_10번째방문지_방문 지역,국내] B_여행4차_10번째방문지_숙박 지역,국내] B_여행4차_10번째방문지_숙박 시설,국내] B_여행4차_11번째방문지_방문 지역,국내] B_여행4차_11번째방문지_숙박 지역,국내] B_여행4차_11번째방문지_숙박 시설,국내] B_여행4차_12번째방문지_방문 지역,국내] B_여행4차_12번째방문지_숙박 지역,국내] B_여행4차_12번째방문지_숙박 시설,국내] B_여행4차_13번째방문지_방문 지역,국내] B_여행4차_13번째방문지_숙박 지역,국내] B_여행4차_13번째방문지_숙박 시설,국내] B_여행4차_14번째방문지_방문 지역,국내] B_여행4차_14번째방문지_숙박 지역,국내] B_여행4차_14번째방문지_숙박 시설,국내] B_여행4차_15번째방문지_방문 지역,국내] B_여행4차_15번째방문지_숙박 지역,국내] B_여행4차_15번째방문지_숙박 시설,국내] B_여행4차_16번째방문지_방문 지역,국내] B_여행4차_16번째방문지_숙박 지역,국내] B_여행4차_16번째방문지_숙박 시설,국내] B_여행4차_17번째방문지_방문 지역,국내] B_여행4차_17번째방문지_숙박 지역,국내] B_여행4차_17번째방문지_숙박 시설,국내] B_여행5차_1번째방문지_방문 지역,국내] B_여행5차_1번째방문지_숙박 지역,국내] B_여행5차_1번째방문지_숙박 시설,국내] B_여행5차_2번째방문지_방문 지역,국내] B_여행5차_2번째방문지_숙박 지역,국내] B_여행5차_2번째방문지_숙박 시설,국내] B_여행5차_3번째방문지_방문 지역,국내] B_여행5차_3번째방문지_숙박 지역,국내] B_여행5차_3번째방문지_숙박 시설,국내] B_여행5차_4번째방문지_방문 지역,국내] B_여행5차_4번째방문지_숙박 지역,국내] B_여행5차_4번째방문지_숙박 시설,국내] B_여행5차_5번째방문지_방문 지역,국내] B_여행5차_5번째방문지_숙박 지역,국내] B_여행5차_5번째방문지_숙박 시설,국내] B_여행5차_6번째방문지_방문 지역,국내] B_여행5차_6번째방문지_숙박 지역,국내] B_여행5차_6번째방문지_숙박 시설,국내] B_여행5차_7번째방문지_방문 지역,국내] B_여행5차_7번째방문지_숙박 지역,국내] B_여행5차_7번째방문지_숙박 시설,국내] B_여행5차_8번째방문지_방문 지역,국내] B_여행5차_8번째방문지_숙박 지역,국내] B_여행5차_8번째방문지_숙박 시설,국내] B_여행5차_9번째방문지_방문 지역,국내] B_여행5차_9번째방문지_숙박 지역,국내] B_여행5차_9번째방문지_숙박 시설,국내] B_여행5차_10번째방문지_방문 지역,국내] B_여행5차_10번째방문지_숙박 지역,국내] B_여행5차_10번째방문지_숙박 시설,국내] B_여행5차_11번째방문지_방문 지역,국내] B_여행5차_11번째방문지_숙박 지역,국내] B_여행5차_11번째방문지_숙박 시설,국내] B_여행5차_12번째방문지_방문 지역,국내] B_여행5차_12번째방문지_숙박 지역,국내] B_여행5차_12번째방문지_숙박 시설,국내] B_여행5차_13번째방문지_방문 지역,국내] B_여행5차_13번째방문지_숙박 지역,국내] B_여행5차_13번째방문지_숙박 시설,국내] B_여행5차_14번째방문지_방문 지역,국내] B_여행5차_14번째방문지_숙박 지역,국내] B_여행5차_14번째방문지_숙박 시설,국내] B_여행5차_15번째방문지_방문 지역,국내] B_여행5차_15번째방문지_숙박 지역,국내] B_여행5차_15번째방문지_숙박 시설,국내] B_여행5차_16번째방문지_방문 지역,국내] B_여행5차_16번째방문지_숙박 지역,국내] B_여행5차_16번째방문지_숙박 시설,국내] B_여행5차_17번째방문지_방문 지역,국내] B_여행5차_17번째방문지_숙박 지역,국내] B_여행5차_17번째방문지_숙박 시설,국내] B_여행1차_주요 이동 교통 수단(지역간),국내] B_여행1차_주요 이동 교통 수단(지역간).1,국내] B_여행1차_주요 이동 교통 수단(지역간).2,국내] B_여행1차_주요 이동 교통 수단(지역내),국내] B_여행1차_주요 이동 교통 수단(지역내).1,국내] B_여행1차_주요 이동 교통 수단(지역내).2,국내] B_여행2차_주요 이동 교통 수단(지역간),국내] B_여행2차_주요 이동 교통 수단(지역간).1,국내] B_여행2차_주요 이동 교통 수단(지역간).2,국내] B_여행2차_주요 이동 교통 수단(지역내),국내] B_여행2차_주요 이동 교통 수단(지역내).1,국내] B_여행2차_주요 이동 교통 수단(지역내).2,국내] B_여행3차_주요 이동 교통 수단(지역간),국내] B_여행3차_주요 이동 교통 수단(지역간).1,국내] B_여행3차_주요 이동 교통 수단(지역간).2,국내] B_여행3차_주요 이동 교통 수단(지역내),국내] B_여행3차_주요 이동 교통 수단(지역내).1,국내] B_여행3차_주요 이동 교통 수단(지역내).2,국내] B_여행4차_주요 이동 교통 수단(지역간),국내] B_여행4차_주요 이동 교통 수단(지역간).1,국내] B_여행4차_주요 이동 교통 수단(지역간).2,국내] B_여행4차_주요 이동 교통 수단(지역내),국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행4차_주요 이동 교통 수단(지역내).2,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역간).1,국내] B_여행5차_주요 이동 교통 수단(지역간).2,국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역내).2,companion_type,travel_activity
0,1,4,4,4,남자,40대,32030,32030,4,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
1,1,4,4,4,남자,30대,32030,NaN,NaN,32030,NaN,NaN,32030,32030,4,32030,NaN,NaN,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
2,1,4,4,4,남자,20대,38090,NaN,NaN,38090,38090,4,38090,NaN,NaN,38090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파"
3,1,4,4,3,남자,40대,31270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양"
4,1,4,4,4,여자,60대,34060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26337,2,5,5,5,남자,40대,38110,38110,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),회의참가/시찰
26338,1,4,4,3,여자,20대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
26339,1,4,4,4,여자,30대,31010,31010,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,6,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
26340,2,4,4,4,남자,50대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"

In [ ]:
# 반려동물 동반 여부의 응답이 결측인 경우 0으로 채움
target_col = "A.[국내] Q6-3. 반려동물 동반 여부"

if target_col in tour.columns:
    tour_df3[target_col] = tour_df3[target_col].fillna(0)

C:\Users\playdata2\AppData\Local\Temp\ipykernel_24448\1441540271.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tour[target_col] = tour[target_col].fillna(0)

In [ ]:
# 1. 각 컬럼별로 '실제 데이터(NaN이 아닌 값)'가 몇 개인지 계산
col_counts = tour_df3.count()

# 2. 유효 데이터 개수가 0인 컬럼명만 리스트로 추출(모든 행이 NaN이거나 값이 없는 컬럼들)
cols_to_delete = col_counts[col_counts == 0].index.tolist()

# 3. 추출된 리스트에 해당하는 컬럼들만 데이터프레임에서 제거(axis=1)
tour2 = tour_df3.drop(columns=cols_to_delete)

# 4. 결과 확인
print(f" 삭제된 빈 컬럼 수: {len(cols_to_delete)}개")
print(f" 남은 컬럼 수: {len(tour2.columns)}개")
print(" 삭제된 컬럼 목록:", cols_to_delete)

🗑️ 삭제된 빈 컬럼 수: 180개
✅ 남은 컬럼 수: 113개
📋 삭제된 컬럼 목록: ['국내]  B_여행1차_11번째방문지_숙박 지역', '국내]  B_여행1차_11번째방문지_숙박 시설', '국내]  B_여행1차_13번째방문지_숙박 지역', '국내]  B_여행1차_13번째방문지_숙박 시설', '국내]  B_여행1차_14번째방문지_방문 지역', '국내]  B_여행1차_14번째방문지_숙박 지역', '국내]  B_여행1차_14번째방문지_숙박 시설', '국내]  B_여행1차_15번째방문지_방문 지역', '국내]  B_여행1차_15번째방문지_숙박 지역', '국내]  B_여행1차_15번째방문지_숙박 시설', '국내]  B_여행1차_16번째방문지_방문 지역', '국내]  B_여행1차_16번째방문지_숙박 지역', '국내]  B_여행1차_16번째방문지_숙박 시설', '국내]  B_여행1차_17번째방문지_방문 지역', '국내]  B_여행1차_17번째방문지_숙박 지역', '국내]  B_여행1차_17번째방문지_숙박 시설', '국내]  B_여행2차_9번째방문지_숙박 지역', '국내]  B_여행2차_9번째방문지_숙박 시설', '국내]  B_여행2차_10번째방문지_숙박 지역', '국내]  B_여행2차_10번째방문지_숙박 시설', '국내]  B_여행2차_11번째방문지_숙박 지역', '국내]  B_여행2차_11번째방문지_숙박 시설', '국내]  B_여행2차_12번째방문지_숙박 지역', '국내]  B_여행2차_12번째방문지_숙박 시설', '국내]  B_여행2차_13번째방문지_방문 지역', '국내]  B_여행2차_13번째방문지_숙박 지역', '국내]  B_여행2차_13번째방문지_숙박 시설', '국내]  B_여행2차_14번째방문지_방문 지역', '국내]  B_여행2차_14번째방문지_숙박 지역', '국내]  B_여행2차_14번째방문지_숙박 시설', '국내]  B_여행2차_15번째방문지_방문 지역', '국내]  B_여행2차_15번째방문지_숙박 지역', '국내]  B_여행2차_15번째방문지_숙박 시설', '국내]  B_여행2차_16번째방문지_방문 지역', '국내]  B_여행2차_16번째방문지_숙박 지역', '국내]  B_여행2차_16번째방문지_숙박 시설', '국내]  B_여행2차_17번째방문지_방문 지역', '국내]  B_여행2차_17번째방문지_숙박 지역', '국내]  B_여행2차_17번째방문지_숙박 시설', '국내]  B_여행3차_3번째방문지_숙박 지역', '국내]  B_여행3차_3번째방문지_숙박 시설', '국내]  B_여행3차_4번째방문지_방문 지역', '국내]  B_여행3차_4번째방문지_숙박 지역', '국내]  B_여행3차_4번째방문지_숙박 시설', '국내]  B_여행3차_5번째방문지_방문 지역', '국내]  B_여행3차_5번째방문지_숙박 지역', '국내]  B_여행3차_5번째방문지_숙박 시설', '국내]  B_여행3차_6번째방문지_방문 지역', '국내]  B_여행3차_6번째방문지_숙박 지역', '국내]  B_여행3차_6번째방문지_숙박 시설', '국내]  B_여행3차_7번째방문지_방문 지역', '국내]  B_여행3차_7번째방문지_숙박 지역', '국내]  B_여행3차_7번째방문지_숙박 시설', '국내]  B_여행3차_8번째방문지_방문 지역', '국내]  B_여행3차_8번째방문지_숙박 지역', '국내]  B_여행3차_8번째방문지_숙박 시설', '국내]  B_여행3차_9번째방문지_방문 지역', '국내]  B_여행3차_9번째방문지_숙박 지역', '국내]  B_여행3차_9번째방문지_숙박 시설', '국내]  B_여행3차_10번째방문지_방문 지역', '국내]  B_여행3차_10번째방문지_숙박 지역', '국내]  B_여행3차_10번째방문지_숙박 시설', '국내]  B_여행3차_11번째방문지_방문 지역', '국내]  B_여행3차_11번째방문지_숙박 지역', '국내]  B_여행3차_11번째방문지_숙박 시설', '국내]  B_여행3차_12번째방문지_방문 지역', '국내]  B_여행3차_12번째방문지_숙박 지역', '국내]  B_여행3차_12번째방문지_숙박 시설', '국내]  B_여행3차_13번째방문지_방문 지역', '국내]  B_여행3차_13번째방문지_숙박 지역', '국내]  B_여행3차_13번째방문지_숙박 시설', '국내]  B_여행3차_14번째방문지_방문 지역', '국내]  B_여행3차_14번째방문지_숙박 지역', '국내]  B_여행3차_14번째방문지_숙박 시설', '국내]  B_여행3차_15번째방문지_방문 지역', '국내]  B_여행3차_15번째방문지_숙박 지역', '국내]  B_여행3차_15번째방문지_숙박 시설', '국내]  B_여행3차_16번째방문지_방문 지역', '국내]  B_여행3차_16번째방문지_숙박 지역', '국내]  B_여행3차_16번째방문지_숙박 시설', '국내]  B_여행3차_17번째방문지_방문 지역', '국내]  B_여행3차_17번째방문지_숙박 지역', '국내]  B_여행3차_17번째방문지_숙박 시설', '국내]  B_여행4차_3번째방문지_숙박 지역', '국내]  B_여행4차_3번째방문지_숙박 시설', '국내]  B_여행4차_4번째방문지_방문 지역', '국내]  B_여행4차_4번째방문지_숙박 지역', '국내]  B_여행4차_4번째방문지_숙박 시설', '국내]  B_여행4차_5번째방문지_방문 지역', '국내]  B_여행4차_5번째방문지_숙박 지역', '국내]  B_여행4차_5번째방문지_숙박 시설', '국내]  B_여행4차_6번째방문지_방문 지역', '국내]  B_여행4차_6번째방문지_숙박 지역', '국내]  B_여행4차_6번째방문지_숙박 시설', '국내]  B_여행4차_7번째방문지_방문 지역', '국내]  B_여행4차_7번째방문지_숙박 지역', '국내]  B_여행4차_7번째방문지_숙박 시설', '국내]  B_여행4차_8번째방문지_방문 지역', '국내]  B_여행4차_8번째방문지_숙박 지역', '국내]  B_여행4차_8번째방문지_숙박 시설', '국내]  B_여행4차_9번째방문지_방문 지역', '국내]  B_여행4차_9번째방문지_숙박 지역', '국내]  B_여행4차_9번째방문지_숙박 시설', '국내]  B_여행4차_10번째방문지_방문 지역', '국내]  B_여행4차_10번째방문지_숙박 지역', '국내]  B_여행4차_10번째방문지_숙박 시설', '국내]  B_여행4차_11번째방문지_방문 지역', '국내]  B_여행4차_11번째방문지_숙박 지역', '국내]  B_여행4차_11번째방문지_숙박 시설', '국내]  B_여행4차_12번째방문지_방문 지역', '국내]  B_여행4차_12번째방문지_숙박 지역', '국내]  B_여행4차_12번째방문지_숙박 시설', '국내]  B_여행4차_13번째방문지_방문 지역', '국내]  B_여행4차_13번째방문지_숙박 지역', '국내]  B_여행4차_13번째방문지_숙박 시설', '국내]  B_여행4차_14번째방문지_방문 지역', '국내]  B_여행4차_14번째방문지_숙박 지역', '국내]  B_여행4차_14번째방문지_숙박 시설', '국내]  B_여행4차_15번째방문지_방문 지역', '국내]  B_여행4차_15번째방문지_숙박 지역', '국내]  B_여행4차_15번째방문지_숙박 시설', '국내]  B_여행4차_16번째방문지_방문 지역', '국내]  B_여행4차_16번째방문지_숙박 지역', '국내]  B_여행4차_16번째방문지_숙박 시설', '국내]  B_여행4차_17번째방문지_방문 지역', '국내]  B_여행4차_17번째방문지_숙박 지역', '국내]  B_여행4차_17번째방문지_숙박 시설', '국내]  B_여행5차_2번째방문지_숙박 지역', '국내]  B_여행5차_2번째방문지_숙박 시설', '국내]  B_여행5차_3번째방문지_방문 지역', '국내]  B_여행5차_3번째방문지_숙박 지역', '국내]  B_여행5차_3번째방문지_숙박 시설', '국내]  B_여행5차_4번째방문지_방문 지역', '국내]  B_여행5차_4번째방문지_숙박 지역', '국내]  B_여행5차_4번째방문지_숙박 시설', '국내]  B_여행5차_5번째방문지_방문 지역', '국내]  B_여행5차_5번째방문지_숙박 지역', '국내]  B_여행5차_5번째방문지_숙박 시설', '국내]  B_여행5차_6번째방문지_방문 지역', '국내]  B_여행5차_6번째방문지_숙박 지역', '국내]  B_여행5차_6번째방문지_숙박 시설', '국내]  B_여행5차_7번째방문지_방문 지역', '국내]  B_여행5차_7번째방문지_숙박 지역', '국내]  B_여행5차_7번째방문지_숙박 시설', '국내]  B_여행5차_8번째방문지_방문 지역', '국내]  B_여행5차_8번째방문지_숙박 지역', '국내]  B_여행5차_8번째방문지_숙박 시설', '국내]  B_여행5차_9번째방문지_방문 지역', '국내]  B_여행5차_9번째방문지_숙박 지역', '국내]  B_여행5차_9번째방문지_숙박 시설', '국내]  B_여행5차_10번째방문지_방문 지역', '국내]  B_여행5차_10번째방문지_숙박 지역', '국내]  B_여행5차_10번째방문지_숙박 시설', '국내]  B_여행5차_11번째방문지_방문 지역', '국내]  B_여행5차_11번째방문지_숙박 지역', '국내]  B_여행5차_11번째방문지_숙박 시설', '국내]  B_여행5차_12번째방문지_방문 지역', '국내]  B_여행5차_12번째방문지_숙박 지역', '국내]  B_여행5차_12번째방문지_숙박 시설', '국내]  B_여행5차_13번째방문지_방문 지역', '국내]  B_여행5차_13번째방문지_숙박 지역', '국내]  B_여행5차_13번째방문지_숙박 시설', '국내]  B_여행5차_14번째방문지_방문 지역', '국내]  B_여행5차_14번째방문지_숙박 지역', '국내]  B_여행5차_14번째방문지_숙박 시설', '국내]  B_여행5차_15번째방문지_방문 지역', '국내]  B_여행5차_15번째방문지_숙박 지역', '국내]  B_여행5차_15번째방문지_숙박 시설', '국내]  B_여행5차_16번째방문지_방문 지역', '국내]  B_여행5차_16번째방문지_숙박 지역', '국내]  B_여행5차_16번째방문지_숙박 시설', '국내]  B_여행5차_17번째방문지_방문 지역', '국내]  B_여행5차_17번째방문지_숙박 지역', '국내]  B_여행5차_17번째방문지_숙박 시설', '국내]  B_여행4차_주요 이동 교통 수단(지역간).1', '국내]  B_여행4차_주요 이동 교통 수단(지역간).2', '국내]  B_여행4차_주요 이동 교통 수단(지역내).2', '국내]  B_여행5차_주요 이동 교통 수단(지역간).1', '국내]  B_여행5차_주요 이동 교통 수단(지역간).2', '국내]  B_여행5차_주요 이동 교통 수단(지역내).2']

In [12]:
tour2

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,국내] B_여행1차_2번째방문지_숙박 지역,국내] B_여행1차_2번째방문지_숙박 시설,국내] B_여행1차_3번째방문지_방문 지역,국내] B_여행1차_3번째방문지_숙박 지역,국내] B_여행1차_3번째방문지_숙박 시설,국내] B_여행1차_4번째방문지_방문 지역,국내] B_여행1차_4번째방문지_숙박 지역,국내] B_여행1차_4번째방문지_숙박 시설,국내] B_여행1차_5번째방문지_방문 지역,국내] B_여행1차_5번째방문지_숙박 지역,국내] B_여행1차_5번째방문지_숙박 시설,국내] B_여행1차_6번째방문지_방문 지역,국내] B_여행1차_6번째방문지_숙박 지역,국내] B_여행1차_6번째방문지_숙박 시설,국내] B_여행1차_7번째방문지_방문 지역,국내] B_여행1차_7번째방문지_숙박 지역,국내] B_여행1차_7번째방문지_숙박 시설,국내] B_여행1차_8번째방문지_방문 지역,국내] B_여행1차_8번째방문지_숙박 지역,국내] B_여행1차_8번째방문지_숙박 시설,국내] B_여행1차_9번째방문지_방문 지역,국내] B_여행1차_9번째방문지_숙박 지역,국내] B_여행1차_9번째방문지_숙박 시설,국내] B_여행1차_10번째방문지_방문 지역,국내] B_여행1차_10번째방문지_숙박 지역,국내] B_여행1차_10번째방문지_숙박 시설,국내] B_여행1차_11번째방문지_방문 지역,국내] B_여행1차_12번째방문지_방문 지역,국내] B_여행1차_12번째방문지_숙박 지역,국내] B_여행1차_12번째방문지_숙박 시설,국내] B_여행1차_13번째방문지_방문 지역,국내] B_여행2차_1번째방문지_방문 지역,국내] B_여행2차_1번째방문지_숙박 지역,국내] B_여행2차_1번째방문지_숙박 시설,국내] B_여행2차_2번째방문지_방문 지역,국내] B_여행2차_2번째방문지_숙박 지역,국내] B_여행2차_2번째방문지_숙박 시설,국내] B_여행2차_3번째방문지_방문 지역,국내] B_여행2차_3번째방문지_숙박 지역,국내] B_여행2차_3번째방문지_숙박 시설,국내] B_여행2차_4번째방문지_방문 지역,국내] B_여행2차_4번째방문지_숙박 지역,국내] B_여행2차_4번째방문지_숙박 시설,국내] B_여행2차_5번째방문지_방문 지역,국내] B_여행2차_5번째방문지_숙박 지역,국내] B_여행2차_5번째방문지_숙박 시설,국내] B_여행2차_6번째방문지_방문 지역,국내] B_여행2차_6번째방문지_숙박 지역,국내] B_여행2차_6번째방문지_숙박 시설,국내] B_여행2차_7번째방문지_방문 지역,국내] B_여행2차_7번째방문지_숙박 지역,국내] B_여행2차_7번째방문지_숙박 시설,국내] B_여행2차_8번째방문지_방문 지역,국내] B_여행2차_8번째방문지_숙박 지역,국내] B_여행2차_8번째방문지_숙박 시설,국내] B_여행2차_9번째방문지_방문 지역,국내] B_여행2차_10번째방문지_방문 지역,국내] B_여행2차_11번째방문지_방문 지역,국내] B_여행2차_12번째방문지_방문 지역,국내] B_여행3차_1번째방문지_방문 지역,국내] B_여행3차_1번째방문지_숙박 지역,국내] B_여행3차_1번째방문지_숙박 시설,국내] B_여행3차_2번째방문지_방문 지역,국내] B_여행3차_2번째방문지_숙박 지역,국내] B_여행3차_2번째방문지_숙박 시설,국내] B_여행3차_3번째방문지_방문 지역,국내] B_여행4차_1번째방문지_방문 지역,국내] B_여행4차_1번째방문지_숙박 지역,국내] B_여행4차_1번째방문지_숙박 시설,국내] B_여행4차_2번째방문지_방문 지역,국내] B_여행4차_2번째방문지_숙박 지역,국내] B_여행4차_2번째방문지_숙박 시설,국내] B_여행4차_3번째방문지_방문 지역,국내] B_여행5차_1번째방문지_방문 지역,국내] B_여행5차_1번째방문지_숙박 지역,국내] B_여행5차_1번째방문지_숙박 시설,국내] B_여행5차_2번째방문지_방문 지역,국내] B_여행1차_주요 이동 교통 수단(지역간),국내] B_여행1차_주요 이동 교통 수단(지역간).1,국내] B_여행1차_주요 이동 교통 수단(지역간).2,국내] B_여행1차_주요 이동 교통 수단(지역내),국내] B_여행1차_주요 이동 교통 수단(지역내).1,국내] B_여행1차_주요 이동 교통 수단(지역내).2,국내] B_여행2차_주요 이동 교통 수단(지역간),국내] B_여행2차_주요 이동 교통 수단(지역간).1,국내] B_여행2차_주요 이동 교통 수단(지역간).2,국내] B_여행2차_주요 이동 교통 수단(지역내),국내] B_여행2차_주요 이동 교통 수단(지역내).1,국내] B_여행2차_주요 이동 교통 수단(지역내).2,국내] B_여행3차_주요 이동 교통 수단(지역간),국내] B_여행3차_주요 이동 교통 수단(지역간).1,국내] B_여행3차_주요 이동 교통 수단(지역간).2,국내] B_여행3차_주요 이동 교통 수단(지역내),국내] B_여행3차_주요 이동 교통 수단(지역내).1,국내] B_여행3차_주요 이동 교통 수단(지역내).2,국내] B_여행4차_주요 이동 교통 수단(지역간),국내] B_여행4차_주요 이동 교통 수단(지역내),국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,companion_type,travel_activity
0,1,4,4,4,남자,40대,32030,32030,4,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
1,1,4,4,4,남자,30대,32030,NaN,NaN,32030,NaN,NaN,32030,32030,4,32030,NaN,NaN,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
2,1,4,4,4,남자,20대,38090,NaN,NaN,38090,38090,4,38090,NaN,NaN,38090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파"
3,1,4,4,3,남자,40대,31270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양"
4,1,4,4,4,여자,60대,34060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26337,2,5,5,5,남자,40대,38110,38110,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),회의참가/시찰
26338,1,4,4,3,여자,20대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
26339,1,4,4,4,여자,30대,31010,31010,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,6,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
26340,2,4,4,4,남자,50대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
26341,2,4,4,3,여자,30대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
import pandas as pd

# 1. 반려동물 동반 여부 치환 (3 -> '동반', 나머지 -> '미동반')
# 'A.[국내] Q6-3. 반려동물 동반 여부' 컬럼 처리
pet_col = "A.[국내] Q6-3. 반려동물 동반 여부"

if pet_col in tour2.columns:
    # 3이면 '동반', 그 외 모든 값(1, 2, 0, NaN 등)은 '미동반'
    tour2[pet_col] = tour2[pet_col].apply(lambda x: '동반' if x == 3 else '미동반')

# 2. 교통수단 매핑 딕셔너리 생성
transport_map = {
    1: '자가용', 2: '철도', 3: '항공기', 4: '선박/해상 교통',
    5: '지하철', 6: '[정기] 고속/시외/시내버스', 7: '[부정기] 전세/관광버스',
    8: '차량대여/렌트', 9: '자전거', 10: '택시', 11: '도보', 12: '기타'
}

# 3. 컬럼명에 '교통수단'이 포함된 모든 컬럼 찾기
transport_cols = [c for c in tour2.columns if '교통수단' in c]

for col in transport_cols:
    tour2[col] = pd.to_numeric(tour2[col], errors='coerce').map(transport_map)
    # 매핑되지 않은 값(결측치 등)은 그대로 두거나 필요시 fillna 사용

In [15]:
tour2

,A.[국내] Q6-3. 반려동물 동반 여부,A.[국내] Q9. 전반적 만족도,A.[국내] Q10. 재방문 의향,A.[국내] Q11. 타인 추천 의향,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,국내] B_여행1차_2번째방문지_숙박 지역,국내] B_여행1차_2번째방문지_숙박 시설,국내] B_여행1차_3번째방문지_방문 지역,국내] B_여행1차_3번째방문지_숙박 지역,국내] B_여행1차_3번째방문지_숙박 시설,국내] B_여행1차_4번째방문지_방문 지역,국내] B_여행1차_4번째방문지_숙박 지역,국내] B_여행1차_4번째방문지_숙박 시설,국내] B_여행1차_5번째방문지_방문 지역,국내] B_여행1차_5번째방문지_숙박 지역,국내] B_여행1차_5번째방문지_숙박 시설,국내] B_여행1차_6번째방문지_방문 지역,국내] B_여행1차_6번째방문지_숙박 지역,국내] B_여행1차_6번째방문지_숙박 시설,국내] B_여행1차_7번째방문지_방문 지역,국내] B_여행1차_7번째방문지_숙박 지역,국내] B_여행1차_7번째방문지_숙박 시설,국내] B_여행1차_8번째방문지_방문 지역,국내] B_여행1차_8번째방문지_숙박 지역,국내] B_여행1차_8번째방문지_숙박 시설,국내] B_여행1차_9번째방문지_방문 지역,국내] B_여행1차_9번째방문지_숙박 지역,국내] B_여행1차_9번째방문지_숙박 시설,국내] B_여행1차_10번째방문지_방문 지역,국내] B_여행1차_10번째방문지_숙박 지역,국내] B_여행1차_10번째방문지_숙박 시설,국내] B_여행1차_11번째방문지_방문 지역,국내] B_여행1차_12번째방문지_방문 지역,국내] B_여행1차_12번째방문지_숙박 지역,국내] B_여행1차_12번째방문지_숙박 시설,국내] B_여행1차_13번째방문지_방문 지역,국내] B_여행2차_1번째방문지_방문 지역,국내] B_여행2차_1번째방문지_숙박 지역,국내] B_여행2차_1번째방문지_숙박 시설,국내] B_여행2차_2번째방문지_방문 지역,국내] B_여행2차_2번째방문지_숙박 지역,국내] B_여행2차_2번째방문지_숙박 시설,국내] B_여행2차_3번째방문지_방문 지역,국내] B_여행2차_3번째방문지_숙박 지역,국내] B_여행2차_3번째방문지_숙박 시설,국내] B_여행2차_4번째방문지_방문 지역,국내] B_여행2차_4번째방문지_숙박 지역,국내] B_여행2차_4번째방문지_숙박 시설,국내] B_여행2차_5번째방문지_방문 지역,국내] B_여행2차_5번째방문지_숙박 지역,국내] B_여행2차_5번째방문지_숙박 시설,국내] B_여행2차_6번째방문지_방문 지역,국내] B_여행2차_6번째방문지_숙박 지역,국내] B_여행2차_6번째방문지_숙박 시설,국내] B_여행2차_7번째방문지_방문 지역,국내] B_여행2차_7번째방문지_숙박 지역,국내] B_여행2차_7번째방문지_숙박 시설,국내] B_여행2차_8번째방문지_방문 지역,국내] B_여행2차_8번째방문지_숙박 지역,국내] B_여행2차_8번째방문지_숙박 시설,국내] B_여행2차_9번째방문지_방문 지역,국내] B_여행2차_10번째방문지_방문 지역,국내] B_여행2차_11번째방문지_방문 지역,국내] B_여행2차_12번째방문지_방문 지역,국내] B_여행3차_1번째방문지_방문 지역,국내] B_여행3차_1번째방문지_숙박 지역,국내] B_여행3차_1번째방문지_숙박 시설,국내] B_여행3차_2번째방문지_방문 지역,국내] B_여행3차_2번째방문지_숙박 지역,국내] B_여행3차_2번째방문지_숙박 시설,국내] B_여행3차_3번째방문지_방문 지역,국내] B_여행4차_1번째방문지_방문 지역,국내] B_여행4차_1번째방문지_숙박 지역,국내] B_여행4차_1번째방문지_숙박 시설,국내] B_여행4차_2번째방문지_방문 지역,국내] B_여행4차_2번째방문지_숙박 지역,국내] B_여행4차_2번째방문지_숙박 시설,국내] B_여행4차_3번째방문지_방문 지역,국내] B_여행5차_1번째방문지_방문 지역,국내] B_여행5차_1번째방문지_숙박 지역,국내] B_여행5차_1번째방문지_숙박 시설,국내] B_여행5차_2번째방문지_방문 지역,국내] B_여행1차_주요 이동 교통 수단(지역간),국내] B_여행1차_주요 이동 교통 수단(지역간).1,국내] B_여행1차_주요 이동 교통 수단(지역간).2,국내] B_여행1차_주요 이동 교통 수단(지역내),국내] B_여행1차_주요 이동 교통 수단(지역내).1,국내] B_여행1차_주요 이동 교통 수단(지역내).2,국내] B_여행2차_주요 이동 교통 수단(지역간),국내] B_여행2차_주요 이동 교통 수단(지역간).1,국내] B_여행2차_주요 이동 교통 수단(지역간).2,국내] B_여행2차_주요 이동 교통 수단(지역내),국내] B_여행2차_주요 이동 교통 수단(지역내).1,국내] B_여행2차_주요 이동 교통 수단(지역내).2,국내] B_여행3차_주요 이동 교통 수단(지역간),국내] B_여행3차_주요 이동 교통 수단(지역간).1,국내] B_여행3차_주요 이동 교통 수단(지역간).2,국내] B_여행3차_주요 이동 교통 수단(지역내),국내] B_여행3차_주요 이동 교통 수단(지역내).1,국내] B_여행3차_주요 이동 교통 수단(지역내).2,국내] B_여행4차_주요 이동 교통 수단(지역간),국내] B_여행4차_주요 이동 교통 수단(지역내),국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,companion_type,travel_activity
0,미동반,4,4,4,남자,40대,32030,32030,4,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
1,미동반,4,4,4,남자,30대,32030,NaN,NaN,32030,NaN,NaN,32030,32030,4,32030,NaN,NaN,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
2,미동반,4,4,4,남자,20대,38090,NaN,NaN,38090,38090,4,38090,NaN,NaN,38090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파"
3,미동반,4,4,3,남자,40대,31270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양"
4,미동반,4,4,4,여자,60대,34060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26337,미동반,5,5,5,남자,40대,38110,38110,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),회의참가/시찰
26338,미동반,4,4,3,여자,20대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
26339,미동반,4,4,4,여자,30대,31010,31010,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,6,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
26340,미동반,4,4,4,남자,50대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
26341,미동반,4,4,3,여자,30대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [32]:
# 삭제할 컬럼 리스트
cols_to_drop = [
    "A.[국내] Q9. 전반적 만족도", 
    "A.[국내] Q10. 재방문 의향", 
    "A.[국내] Q11. 타인 추천 의향"
]

# 컬럼 삭제 (axis=1 또는 columns 파라미터 사용)
# inplace=True를 설정하면 원본 데이터프레임(tour_df2)이 즉시 수정됩니다.
tour2.drop(columns=cols_to_drop, inplace=True)

In [ ]:
import pandas as pd

# 1. 숙박 시설 매핑 딕셔너리 생성
accommodation_map = {
    1: '호텔', 2: '모텔/여관', 3: '펜션', 4: '콘도미니엄/리조트',
    5: '유스호스텔', 6: '야영(캠핑)', 7: '연수원/수련원', 8: '전통 한옥 숙박시설',
    9: '게스트 하우스', 10: '민박', 11: '자연휴양림 내 숙박시설',
    12: '가족/친지집', 13: '무박 여행', 14: '기타'
}

# 2. 컬럼명에 '숙박 시설'이 포함된 모든 컬럼 찾기
acc_cols = [c for c in tour2.columns if '숙박 시설' in c or '숙박시설' in c]

# 3. 해당 컬럼들의 값을 한꺼번에 치환
for col in acc_cols:
    # 1) 숫자로 변환 (결측치는 NaN 처리)
    tour2[col] = pd.to_numeric(tour2[col], errors='coerce')
    
    # 2) 딕셔너리를 사용하여 텍스트로 치환
    tour2[col] = tour2[col].map(accommodation_map)

In [34]:
tour2

,A.[국내] Q6-3. 반려동물 동반 여부,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,국내] B_여행1차_2번째방문지_숙박 지역,국내] B_여행1차_2번째방문지_숙박 시설,국내] B_여행1차_3번째방문지_방문 지역,국내] B_여행1차_3번째방문지_숙박 지역,국내] B_여행1차_3번째방문지_숙박 시설,국내] B_여행1차_4번째방문지_방문 지역,국내] B_여행1차_4번째방문지_숙박 지역,국내] B_여행1차_4번째방문지_숙박 시설,국내] B_여행1차_5번째방문지_방문 지역,국내] B_여행1차_5번째방문지_숙박 지역,국내] B_여행1차_5번째방문지_숙박 시설,국내] B_여행1차_6번째방문지_방문 지역,국내] B_여행1차_6번째방문지_숙박 지역,국내] B_여행1차_6번째방문지_숙박 시설,국내] B_여행1차_7번째방문지_방문 지역,국내] B_여행1차_7번째방문지_숙박 지역,국내] B_여행1차_7번째방문지_숙박 시설,국내] B_여행1차_8번째방문지_방문 지역,국내] B_여행1차_8번째방문지_숙박 지역,국내] B_여행1차_8번째방문지_숙박 시설,국내] B_여행1차_9번째방문지_방문 지역,국내] B_여행1차_9번째방문지_숙박 지역,국내] B_여행1차_9번째방문지_숙박 시설,국내] B_여행1차_10번째방문지_방문 지역,국내] B_여행1차_10번째방문지_숙박 지역,국내] B_여행1차_10번째방문지_숙박 시설,국내] B_여행1차_11번째방문지_방문 지역,국내] B_여행1차_12번째방문지_방문 지역,국내] B_여행1차_12번째방문지_숙박 지역,국내] B_여행1차_12번째방문지_숙박 시설,국내] B_여행1차_13번째방문지_방문 지역,국내] B_여행2차_1번째방문지_방문 지역,국내] B_여행2차_1번째방문지_숙박 지역,국내] B_여행2차_1번째방문지_숙박 시설,국내] B_여행2차_2번째방문지_방문 지역,국내] B_여행2차_2번째방문지_숙박 지역,국내] B_여행2차_2번째방문지_숙박 시설,국내] B_여행2차_3번째방문지_방문 지역,국내] B_여행2차_3번째방문지_숙박 지역,국내] B_여행2차_3번째방문지_숙박 시설,국내] B_여행2차_4번째방문지_방문 지역,국내] B_여행2차_4번째방문지_숙박 지역,국내] B_여행2차_4번째방문지_숙박 시설,국내] B_여행2차_5번째방문지_방문 지역,국내] B_여행2차_5번째방문지_숙박 지역,국내] B_여행2차_5번째방문지_숙박 시설,국내] B_여행2차_6번째방문지_방문 지역,국내] B_여행2차_6번째방문지_숙박 지역,국내] B_여행2차_6번째방문지_숙박 시설,국내] B_여행2차_7번째방문지_방문 지역,국내] B_여행2차_7번째방문지_숙박 지역,국내] B_여행2차_7번째방문지_숙박 시설,국내] B_여행2차_8번째방문지_방문 지역,국내] B_여행2차_8번째방문지_숙박 지역,국내] B_여행2차_8번째방문지_숙박 시설,국내] B_여행2차_9번째방문지_방문 지역,국내] B_여행2차_10번째방문지_방문 지역,국내] B_여행2차_11번째방문지_방문 지역,국내] B_여행2차_12번째방문지_방문 지역,국내] B_여행3차_1번째방문지_방문 지역,국내] B_여행3차_1번째방문지_숙박 지역,국내] B_여행3차_1번째방문지_숙박 시설,국내] B_여행3차_2번째방문지_방문 지역,국내] B_여행3차_2번째방문지_숙박 지역,국내] B_여행3차_2번째방문지_숙박 시설,국내] B_여행3차_3번째방문지_방문 지역,국내] B_여행4차_1번째방문지_방문 지역,국내] B_여행4차_1번째방문지_숙박 지역,국내] B_여행4차_1번째방문지_숙박 시설,국내] B_여행4차_2번째방문지_방문 지역,국내] B_여행4차_2번째방문지_숙박 지역,국내] B_여행4차_2번째방문지_숙박 시설,국내] B_여행4차_3번째방문지_방문 지역,국내] B_여행5차_1번째방문지_방문 지역,국내] B_여행5차_1번째방문지_숙박 지역,국내] B_여행5차_1번째방문지_숙박 시설,국내] B_여행5차_2번째방문지_방문 지역,국내] B_여행1차_주요 이동 교통 수단(지역간),국내] B_여행1차_주요 이동 교통 수단(지역간).1,국내] B_여행1차_주요 이동 교통 수단(지역간).2,국내] B_여행1차_주요 이동 교통 수단(지역내),국내] B_여행1차_주요 이동 교통 수단(지역내).1,국내] B_여행1차_주요 이동 교통 수단(지역내).2,국내] B_여행2차_주요 이동 교통 수단(지역간),국내] B_여행2차_주요 이동 교통 수단(지역간).1,국내] B_여행2차_주요 이동 교통 수단(지역간).2,국내] B_여행2차_주요 이동 교통 수단(지역내),국내] B_여행2차_주요 이동 교통 수단(지역내).1,국내] B_여행2차_주요 이동 교통 수단(지역내).2,국내] B_여행3차_주요 이동 교통 수단(지역간),국내] B_여행3차_주요 이동 교통 수단(지역간).1,국내] B_여행3차_주요 이동 교통 수단(지역간).2,국내] B_여행3차_주요 이동 교통 수단(지역내),국내] B_여행3차_주요 이동 교통 수단(지역내).1,국내] B_여행3차_주요 이동 교통 수단(지역내).2,국내] B_여행4차_주요 이동 교통 수단(지역간),국내] B_여행4차_주요 이동 교통 수단(지역내),국내] B_여행4차_주요 이동 교통 수단(지역내).1,국내] B_여행5차_주요 이동 교통 수단(지역간),국내] B_여행5차_주요 이동 교통 수단(지역내),국내] B_여행5차_주요 이동 교통 수단(지역내).1,companion_type,travel_activity
0,미동반,남자,40대,32030,32030,콘도미니엄/리조트,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
1,미동반,남자,30대,32030,NaN,NaN,32030,NaN,NaN,32030,32030,콘도미니엄/리조트,32030,NaN,NaN,32030,NaN,NaN,32030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
2,미동반,남자,20대,38090,NaN,NaN,38090,38090,콘도미니엄/리조트,38090,NaN,NaN,38090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파"
3,미동반,남자,40대,31270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양"
4,미동반,여자,60대,34060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26337,미동반,남자,40대,38110,38110,호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),회의참가/시찰
26338,미동반,여자,20대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,친구,"음식관광, 휴식/휴양"
26339,미동반,여자,30대,31010,31010,가족/친지집,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,6,NaN,10,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,단독(없음),"시티투어, 가족/친지 방문"
26340,미동반,남자,50대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
26341,미동반,여자,30대,39010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
# 1. 삭제할 키워드 정의
# '4차 여행', '5차 여행'이 포함된 컬럼과 '10번째'부터 '17번째'까지의 방문지 컬럼을 타겟팅
drop_keywords = [
    "4차 여행", "5차 여행", 
    "10번째방문지", "11번째방문지", "12번째방문지", "13번째방문지", 
    "14번째방문지", "15번째방문지", "16번째방문지", "17번째방문지"
]

# 2. 전체 컬럼 중 해당 키워드가 하나라도 포함된 컬럼명 리스트 생성
cols_to_drop = [c for c in tour2.columns if any(k in c for k in drop_keywords)]

# 3. 해당 컬럼들 삭제
tour2 = tour2.drop(columns=cols_to_drop)

print(f" 삭제된 컬럼 수: {len(cols_to_drop)}개")
print(f" 남은 컬럼 수: {len(tour2.columns)}개")

🗑️ 삭제된 컬럼 수: 11개
✅ 남은 컬럼 수: 99개

In [ ]:
import pandas as pd

# 1. 분석할 교통수단 컬럼 리스트 (1차~3차 여행)
# .1, .2 등 복수 응답 컬럼을 모두 포함
transport_target_cols = [c for c in tour2.columns if '주요 이동 교통 수단' in c]

print(" [교통수단 응답 분포 확인]")
for col in transport_target_cols:
    # 해당 컬럼에 실제 데이터가 있는지 먼저 확인
    if tour2[col].count() > 0:
        print(f"\n 컬럼명: {col}")
        # value_counts()로 1~12번 값이 각각 몇 개인지 계산
        # sort_index()를 통해 번호순으로 정렬
        counts = tour2[col].value_counts().sort_index()
        print(counts)
    else:
        print(f"\n 컬럼명: {col} (데이터 없음/전부 결측치)")

# 2. 전체적인 데이터 밀도 요약 (표 형태)
summary_transport = tour2[transport_target_cols].count().to_frame(name='유효 응답 수')
print("\n---  교통수단 데이터 요약 ---")
print(summary_transport)

📊 [교통수단 응답 분포 확인]

📍 컬럼명: 국내]  B_여행1차_주요 이동 교통 수단(지역간)
국내]  B_여행1차_주요 이동 교통 수단(지역간)
1     22687
2       432
3       696
4        89
5       566
6       939
7       447
8        52
9        50
10       89
11      280
12       15
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행1차_주요 이동 교통 수단(지역간).1
국내]  B_여행1차_주요 이동 교통 수단(지역간).1
1      401
2      113
3      255
4      110
5      110
6      160
7       35
8       67
9        5
10     153
11    1394
12       1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행1차_주요 이동 교통 수단(지역간).2
국내]  B_여행1차_주요 이동 교통 수단(지역간).2
1      5
2     12
3     21
4      4
5      6
6     13
7      4
8     36
10    16
11    97
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행1차_주요 이동 교통 수단(지역내)
국내]  B_여행1차_주요 이동 교통 수단(지역내)
1     19055
2        55
3         1
4        47
5       471
6       400
7       504
8       652
9        97
10      351
11     4699
12       10
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행1차_주요 이동 교통 수단(지역내).1
국내]  B_여행1차_주요 이동 교통 수단(지역내).1
1     1773
2       16
4      101
5       98
6      115
7       53
8       39
9       19
10     148
11    9472
12       3
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행1차_주요 이동 교통 수단(지역내).2
국내]  B_여행1차_주요 이동 교통 수단(지역내).2
1      18
2       4
4      41
5      11
6      26
7       3
8       1
9      12
10     37
11    106
12      5
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행2차_주요 이동 교통 수단(지역간)
국내]  B_여행2차_주요 이동 교통 수단(지역간)
1     1026
2       19
3       10
4        3
5       18
6       38
7       21
9        2
11       6
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행2차_주요 이동 교통 수단(지역간).1
국내]  B_여행2차_주요 이동 교통 수단(지역간).1
1      2
2      4
3      5
4      1
5      8
6     10
10     3
11    47
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행2차_주요 이동 교통 수단(지역간).2
국내]  B_여행2차_주요 이동 교통 수단(지역간).2
2     1
5     2
6     2
8     1
10    1
11    5
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행2차_주요 이동 교통 수단(지역내)
국내]  B_여행2차_주요 이동 교통 수단(지역내)
1     756
2       2
4       2
5       8
6      12
7      15
8      10
9       3
10     18
11    317
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행2차_주요 이동 교통 수단(지역내).1
국내]  B_여행2차_주요 이동 교통 수단(지역내).1
1      97
4       1
5       4
6       6
7       2
8       1
9       1
10      6
11    353
12      1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행2차_주요 이동 교통 수단(지역내).2
국내]  B_여행2차_주요 이동 교통 수단(지역내).2
4     1
5     1
6     2
8     1
10    1
11    1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행3차_주요 이동 교통 수단(지역간)
국내]  B_여행3차_주요 이동 교통 수단(지역간)
1     77
5      4
6      6
7      3
11     1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행3차_주요 이동 교통 수단(지역간).1
국내]  B_여행3차_주요 이동 교통 수단(지역간).1
2    1
5    2
6    1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행3차_주요 이동 교통 수단(지역간).2
국내]  B_여행3차_주요 이동 교통 수단(지역간).2
6    1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행3차_주요 이동 교통 수단(지역내)
국내]  B_여행3차_주요 이동 교통 수단(지역내)
1     51
6      2
7      2
11    36
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행3차_주요 이동 교통 수단(지역내).1
국내]  B_여행3차_주요 이동 교통 수단(지역내).1
1      4
10     1
11    28
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행3차_주요 이동 교통 수단(지역내).2
국내]  B_여행3차_주요 이동 교통 수단(지역내).2
11    1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행4차_주요 이동 교통 수단(지역간)
국내]  B_여행4차_주요 이동 교통 수단(지역간)
1    13
5     1
6     1
7     1
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행4차_주요 이동 교통 수단(지역내)
국내]  B_여행4차_주요 이동 교통 수단(지역내)
1     10
11     6
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행4차_주요 이동 교통 수단(지역내).1
국내]  B_여행4차_주요 이동 교통 수단(지역내).1
11    2
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행5차_주요 이동 교통 수단(지역간)
국내]  B_여행5차_주요 이동 교통 수단(지역간)
1    4
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행5차_주요 이동 교통 수단(지역내)
국내]  B_여행5차_주요 이동 교통 수단(지역내)
1     2
11    2
Name: count, dtype: int64

📍 컬럼명: 국내]  B_여행5차_주요 이동 교통 수단(지역내).1
국내]  B_여행5차_주요 이동 교통 수단(지역내).1
11    1
Name: count, dtype: int64

--- 📝 교통수단 데이터 요약 ---
                                유효 응답 수
국내]  B_여행1차_주요 이동 교통 수단(지역간)      26342
국내]  B_여행1차_주요 이동 교통 수단(지역간).1     2804
국내]  B_여행1차_주요 이동 교통 수단(지역간).2      214
국내]  B_여행1차_주요 이동 교통 수단(지역내)      26342
국내]  B_여행1차_주요 이동 교통 수단(지역내).1    11837
국내]  B_여행1차_주요 이동 교통 수단(지역내).2      264
국내]  B_여행2차_주요 이동 교통 수단(지역간)       1143
국내]  B_여행2차_주요 이동 교통 수단(지역간).1       80
국내]  B_여행2차_주요 이동 교통 수단(지역간).2       12
국내]  B_여행2차_주요 이동 교통 수단(지역내)       1143
국내]  B_여행2차_주요 이동 교통 수단(지역내).1      472
국내]  B_여행2차_주요 이동 교통 수단(지역내).2        7
국내]  B_여행3차_주요 이동 교통 수단(지역간)         91
국내]  B_여행3차_주요 이동 교통 수단(지역간).1        4
국내]  B_여행3차_주요 이동 교통 수단(지역간).2        1
국내]  B_여행3차_주요 이동 교통 수단(지역내)         91
국내]  B_여행3차_주요 이동 교통 수단(지역내).1       33
국내]  B_여행3차_주요 이동 교통 수단(지역내).2        1
국내]  B_여행4차_주요 이동 교통 수단(지역간)         16
국내]  B_여행4차_주요 이동 교통 수단(지역내)         16
국내]  B_여행4차_주요 이동 교통 수단(지역내).1        2
국내]  B_여행5차_주요 이동 교통 수단(지역간)          4
국내]  B_여행5차_주요 이동 교통 수단(지역내)          4
국내]  B_여행5차_주요 이동 교통 수단(지역내).1        1

In [ ]:
import pandas as pd
import numpy as np

tour3 = tour2.copy()

# 4차, 5차 관련 교통수단 컬럼 리스트 정의 및 삭제
drop_transport_cols = [
    '국내]  B_여행4차_주요 이동 교통 수단(지역간)',
    '국내]  B_여행4차_주요 이동 교통 수단(지역내)',
    '국내]  B_여행4차_주요 이동 교통 수단(지역내).1',
    '국내]  B_여행5차_주요 이동 교통 수단(지역간)',
    '국내]  B_여행5차_주요 이동 교통 수단(지역내)',
    '국내]  B_여행5차_주요 이동 교통 수단(지역내).1'
]
existing_drop_cols = [c for c in drop_transport_cols if c in tour3.columns]
tour3.drop(columns=existing_drop_cols, inplace=True)

# 교통수단 매핑 딕셔너리 (키값을 숫자로 설정)
transport_map = {
    1: '자가용', 2: '철도', 3: '항공기', 4: '선박/해상 교통',
    5: '지하철', 6: '[정기] 고속/시외/시내버스', 7: '[부정기] 전세/관광버스',
    8: '차량대여/렌트', 9: '자전거', 10: '택시', 11: '도보', 12: '기타'
}

# 남은 교통수단 컬럼들 처리 (1~3차)
target_cols = [c for c in tour3.columns if '주요 이동 교통 수단' in c]

for col in target_cols:
    tour3[col] = pd.to_numeric(tour3[col], errors='coerce')
    tour3[col] = tour3[col].map(transport_map)

print(" 4-5차 컬럼 삭제 및 1-3차 매핑 완료")
print(f" tour3의 교통수단 결측치 수:\n{tour3[target_cols].isnull().sum()}")
print(f"\n 매핑 결과 샘플:\n{tour3[target_cols].dropna(how='all').head()}")

✅ 4-5차 컬럼 삭제 및 1-3차 매핑 완료
📊 tour3의 교통수단 결측치 수:
국내]  B_여행1차_주요 이동 교통 수단(지역간)          0
국내]  B_여행1차_주요 이동 교통 수단(지역간).1    23538
국내]  B_여행1차_주요 이동 교통 수단(지역간).2    26128
국내]  B_여행1차_주요 이동 교통 수단(지역내)          0
국내]  B_여행1차_주요 이동 교통 수단(지역내).1    14505
국내]  B_여행1차_주요 이동 교통 수단(지역내).2    26078
국내]  B_여행2차_주요 이동 교통 수단(지역간)      25199
국내]  B_여행2차_주요 이동 교통 수단(지역간).1    26262
국내]  B_여행2차_주요 이동 교통 수단(지역간).2    26330
국내]  B_여행2차_주요 이동 교통 수단(지역내)      25199
국내]  B_여행2차_주요 이동 교통 수단(지역내).1    25870
국내]  B_여행2차_주요 이동 교통 수단(지역내).2    26335
국내]  B_여행3차_주요 이동 교통 수단(지역간)      26251
국내]  B_여행3차_주요 이동 교통 수단(지역간).1    26338
국내]  B_여행3차_주요 이동 교통 수단(지역간).2    26341
국내]  B_여행3차_주요 이동 교통 수단(지역내)      26251
국내]  B_여행3차_주요 이동 교통 수단(지역내).1    26309
국내]  B_여행3차_주요 이동 교통 수단(지역내).2    26341
dtype: int64

👀 매핑 결과 샘플:
  국내]  B_여행1차_주요 이동 교통 수단(지역간) 국내]  B_여행1차_주요 이동 교통 수단(지역간).1  \
0                          자가용                            NaN
1                          자가용                            NaN
2                           철도                            NaN
3                          자가용                            NaN
4                           도보                            NaN

  국내]  B_여행1차_주요 이동 교통 수단(지역간).2 국내]  B_여행1차_주요 이동 교통 수단(지역내)  \
0                            NaN                          자가용
1                            NaN                          자가용
2                            NaN                           택시
3                            NaN                          자가용
4                            NaN                [부정기] 전세/관광버스

  국내]  B_여행1차_주요 이동 교통 수단(지역내).1 국내]  B_여행1차_주요 이동 교통 수단(지역내).2  \
0                             도보                            NaN
1                            NaN                            NaN
2                [정기] 고속/시외/시내버스                            NaN
3                             도보                            NaN
4                            NaN                            NaN

  국내]  B_여행2차_주요 이동 교통 수단(지역간) 국내]  B_여행2차_주요 이동 교통 수단(지역간).1  \
0                          NaN                            NaN
1                          NaN                            NaN
2                          NaN                            NaN
3                          NaN                            NaN
4                          NaN                            NaN

  국내]  B_여행2차_주요 이동 교통 수단(지역간).2 국내]  B_여행2차_주요 이동 교통 수단(지역내)  \
0                            NaN                          NaN
1                            NaN                          NaN
2                            NaN                          NaN
3                            NaN                          NaN
4                            NaN                          NaN

  국내]  B_여행2차_주요 이동 교통 수단(지역내).1 국내]  B_여행2차_주요 이동 교통 수단(지역내).2  \
0                            NaN                            NaN
1                            NaN                            NaN
2                            NaN                            NaN
3                            NaN                            NaN
4                            NaN                            NaN

  국내]  B_여행3차_주요 이동 교통 수단(지역간) 국내]  B_여행3차_주요 이동 교통 수단(지역간).1  \
0                          NaN                            NaN
1                          NaN                            NaN
2                          NaN                            NaN
3                          NaN                            NaN
4                          NaN                            NaN

  국내]  B_여행3차_주요 이동 교통 수단(지역간).2 국내]  B_여행3차_주요 이동 교통 수단(지역내)  \
0                            NaN                          NaN
1                            NaN                          NaN
2                            NaN                          NaN
3                            NaN                          NaN
4                            NaN                          NaN

  국내]  B_여행3차_주요 이동 교통 수단(지역내).1 국내]  B_여행3차_주요 이동 교통 수단(지역내).2
0                            NaN                            NaN
1                            NaN                            NaN
2                            NaN                            NaN
3                            NaN                            NaN
4                            NaN                            NaN

In [ ]:
# 1. 컬럼명에서 공백을 제거하고 '교통수단'이 포함된 것만 추출
transport_cols = [c for c in tour3.columns if '교통수단' in c.replace(" ", "")]

# 2. 결측치가 20,000개 이상인 컬럼 식별
cols_to_drop = [col for col in transport_cols if tour3[col].isnull().sum() >= 20000]

# 3. 해당 컬럼들 삭제
if cols_to_drop:
    tour3.drop(columns=cols_to_drop, inplace=True)
    print(f" 삭제된 교통수단 컬럼 ({len(cols_to_drop)}개): {cols_to_drop}")
else:
    print("⚠️ 삭제할 조건(결측치 2만개 이상)에 맞는 교통수단 컬럼이 없습니다.")

remaining = [c for c in tour3.columns if '교통수단' in c.replace(" ", "")]
print(f" 현재 tour3에 남은 교통수단 컬럼: {remaining}")

🗑️ 삭제된 교통수단 컬럼 (15개): ['국내]  B_여행1차_주요 이동 교통 수단(지역간).1', '국내]  B_여행1차_주요 이동 교통 수단(지역간).2', '국내]  B_여행1차_주요 이동 교통 수단(지역내).2', '국내]  B_여행2차_주요 이동 교통 수단(지역간)', '국내]  B_여행2차_주요 이동 교통 수단(지역간).1', '국내]  B_여행2차_주요 이동 교통 수단(지역간).2', '국내]  B_여행2차_주요 이동 교통 수단(지역내)', '국내]  B_여행2차_주요 이동 교통 수단(지역내).1', '국내]  B_여행2차_주요 이동 교통 수단(지역내).2', '국내]  B_여행3차_주요 이동 교통 수단(지역간)', '국내]  B_여행3차_주요 이동 교통 수단(지역간).1', '국내]  B_여행3차_주요 이동 교통 수단(지역간).2', '국내]  B_여행3차_주요 이동 교통 수단(지역내)', '국내]  B_여행3차_주요 이동 교통 수단(지역내).1', '국내]  B_여행3차_주요 이동 교통 수단(지역내).2']
✅ 현재 tour3에 남은 교통수단 컬럼: ['국내]  B_여행1차_주요 이동 교통 수단(지역간)', '국내]  B_여행1차_주요 이동 교통 수단(지역내)', '국내]  B_여행1차_주요 이동 교통 수단(지역내).1']

In [ ]:
# 1. 분석할 컬럼 리스트 정의 (방문 지역, 숙박 지역, 숙박 시설 키워드 포함)
target_keywords = ['방문 지역', '숙박 지역', '숙박 시설']
visit_cols = [c for c in tour3.columns if any(k in c for k in target_keywords)]

# 2. 결측치 개수 세기
null_counts = tour3[visit_cols].isnull().sum()
null_summary = null_counts.to_frame(name='결측치 수')
null_summary['유효 데이터 수'] = tour3[visit_cols].count()

print(" [방문지 및 숙박 정보 결측치 현황]")
print(null_summary)

📊 [방문지 및 숙박 정보 결측치 현황]
                          결측치 수  유효 데이터 수
국내]  B_여행1차_1번째방문지_방문 지역      0     26342
국내]  B_여행1차_1번째방문지_숙박 지역  17884      8458
국내]  B_여행1차_1번째방문지_숙박 시설  17884      8458
국내]  B_여행1차_2번째방문지_방문 지역  16925      9417
국내]  B_여행1차_2번째방문지_숙박 지역  23879      2463
...                         ...       ...
국내]  B_여행4차_3번째방문지_방문 지역  26341         1
국내]  B_여행5차_1번째방문지_방문 지역  26338         4
국내]  B_여행5차_1번째방문지_숙박 지역  26339         3
국내]  B_여행5차_1번째방문지_숙박 시설  26339         3
국내]  B_여행5차_2번째방문지_방문 지역  26341         1

[70 rows x 2 columns]

In [ ]:
import pandas as pd

tour4 = tour3.copy()

# 2. 4차, 5차 여행 관련 모든 컬럼 삭제 (방문지, 숙박, 교통 등 전체)
cols_to_drop_45 = [c for c in tour4.columns if '4차 여행' in c or '5차 여행' in c]
tour4.drop(columns=cols_to_drop_45, inplace=True, errors='ignore')

# 3. 방문 지역, 숙박 지역, 숙박 시설 관련 컬럼 중 결측치가 20,000개 이상인 컬럼 식별
target_keywords = ['방문 지역', '숙박 지역', '숙박 시설']
visit_accommodation_cols = [c for c in tour4.columns if any(k in c for k in target_keywords)]

cols_to_drop_null = [col for col in visit_accommodation_cols if tour4[col].isnull().sum() >= 20000]

# 4. 해당 컬럼들 삭제
tour4.drop(columns=cols_to_drop_null, inplace=True)

remaining_visit_cols = [c for c in tour4.columns if any(k in c for k in target_keywords)]

print(f" [처리 완료]")
print(f" 삭제된 4~5차 컬럼: {len(cols_to_drop_45)}개")
print(f" 결측치 과다(2만↑)로 삭제된 방문/숙박 컬럼: {len(cols_to_drop_null)}개")
print(f" 최종 남은 방문/숙박 컬럼 수: {len(remaining_visit_cols)}개")
print("\n tour4 핵심 컬럼 예시:")
print(tour4.filter(like='1차_1번째방문지').columns.tolist())

✅ [처리 완료]
🗑️ 삭제된 4~5차 컬럼: 0개
🗑️ 결측치 과다(2만↑)로 삭제된 방문/숙박 컬럼: 66개
⭐ 최종 남은 방문/숙박 컬럼 수: 4개

👀 tour4 핵심 컬럼 예시:
['국내]  B_여행1차_1번째방문지_방문 지역', '국내]  B_여행1차_1번째방문지_숙박 지역', '국내]  B_여행1차_1번째방문지_숙박 시설']

In [45]:
tour4

,A.[국내] Q6-3. 반려동물 동반 여부,공통] 성별,공통] 연령,국내] B_여행1차_1번째방문지_방문 지역,국내] B_여행1차_1번째방문지_숙박 지역,국내] B_여행1차_1번째방문지_숙박 시설,국내] B_여행1차_2번째방문지_방문 지역,국내] B_여행1차_주요 이동 교통 수단(지역간),국내] B_여행1차_주요 이동 교통 수단(지역내),국내] B_여행1차_주요 이동 교통 수단(지역내).1,companion_type,travel_activity
0,미동반,남자,40대,32030,32030,콘도미니엄/리조트,32030,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
1,미동반,남자,30대,32030,NaN,NaN,32030,자가용,자가용,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
2,미동반,남자,20대,38090,NaN,NaN,38090,철도,택시,[정기] 고속/시외/시내버스,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파"
3,미동반,남자,40대,31270,NaN,NaN,NaN,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양"
4,미동반,여자,60대,34060,NaN,NaN,NaN,도보,[부정기] 전세/관광버스,NaN,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠"
...,...,...,...,...,...,...,...,...,...,...,...,...
26337,미동반,남자,40대,38110,38110,호텔,NaN,항공기,자가용,NaN,단독(없음),회의참가/시찰
26338,미동반,여자,20대,39010,NaN,NaN,NaN,자가용,자가용,NaN,친구,"음식관광, 휴식/휴양"
26339,미동반,여자,30대,31010,31010,가족/친지집,NaN,항공기,택시,[정기] 고속/시외/시내버스,단독(없음),"시티투어, 가족/친지 방문"
26340,미동반,남자,50대,39010,NaN,NaN,NaN,자가용,자가용,NaN,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
26341,미동반,여자,30대,39010,NaN,NaN,NaN,자가용,자가용,NaN,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
# 1. 현재 tour4의 모든 컬럼명을 가져와서 공백을 제거한 버전과 매핑
current_cols = tour4.columns.tolist()

# 2. 핵심 키워드 기반 매핑 사전
# '한글키워드': '영문명'
keyword_map = {
    '성별': 'gender',
    '연령': 'age_group',
    '1차_1번째방문지_방문지역': 'trip1_visit1_area',
    '1차_1번째방문지_숙박지역': 'trip1_stay1_area',
    '1차_1번째방문지_숙박시설': 'trip1_stay1_type',
    '1차_2번째방문지_방문지역': 'trip1_visit2_area',
    '1차_주요이동교통수단(지역간)': 'trip1_transport_intercity',
    '1차_주요이동교통수단(지역내)': 'trip1_transport_intracity_1',
    '1차_주요이동교통수단(지역내).1': 'trip1_transport_intracity_2'
}

# 3. 실제 컬럼명을 순회하며 매핑 적용
new_columns = []
for col in current_cols:
    # 현재 컬럼명에서 공백 제거
    clean_col = col.replace(" ", "")
    
    # keyword_map의 키가 clean_col 안에 포함되어 있는지 확인
    matched = False
    for k, v in keyword_map.items():
        if k in clean_col:
            new_columns.append(v)
            matched = True
            break
    
    if not matched:
        new_columns.append(col)

# 4. 컬럼명 일괄 교체
tour4.columns = new_columns

print("✅ 최종 변경된 컬럼 목록:")
print([c for c in tour4.columns if c in keyword_map.values() or c == 'with_pet'])

✅ 최종 변경된 컬럼 목록:
['with_pet', 'gender', 'age_group', 'trip1_visit1_area', 'trip1_stay1_area', 'trip1_stay1_type', 'trip1_visit2_area', 'trip1_transport_intercity', 'trip1_transport_intracity_1', 'trip1_transport_intracity_1']

In [ ]:
# 1. tour4 데이터프레임 전체의 결측치(NaN)를 'N'으로 일괄 변경
# fillna는 기존 데이터 타입을 유지하려 하지만, 'N'이라는 문자열이 들어가면 
# 숫자 컬럼들도 자동으로 object(문자열) 타입으로 변환됩니다.
tour4 = tour4.fillna('N')

# 2. 전체 데이터프레임에 결측치가 남아있는지 확인
print(f" 전체 결측치 개수: {tour4.isnull().sum().sum()}")

# 3. 데이터 타입 변화 확인
print("\n 주요 컬럼 데이터 타입 확인:")
print(tour4.dtypes.head(10))
print("\n tour4 하위 데이터 샘플:")
print(tour4.tail())

📊 전체 결측치 개수: 0

📝 주요 컬럼 데이터 타입 확인:
with_pet                       object
gender                         object
age_group                      object
trip1_visit1_area               int64
trip1_stay1_area               object
trip1_stay1_type               object
trip1_visit2_area              object
trip1_transport_intercity      object
trip1_transport_intracity_1    object
trip1_transport_intracity_1    object
dtype: object

👀 tour4 하위 데이터 샘플:
      with_pet gender age_group  trip1_visit1_area trip1_stay1_area  \
26337      미동반     남자       40대              38110            38110
26338      미동반     여자       20대              39010                N
26339      미동반     여자       30대              31010            31010
26340      미동반     남자       50대              39010                N
26341      미동반     여자       30대              39010                N

      trip1_stay1_type trip1_visit2_area trip1_transport_intercity  \
26337               호텔                 N                       항공기
26338                N                 N                       자가용
26339           가족/친지집                 N                       항공기
26340                N                 N                       자가용
26341                N                 N                       자가용

      trip1_transport_intracity_1 trip1_transport_intracity_1 companion_type  \
26337                         자가용                           N         단독(없음)
26338                         자가용                           N             친구
26339                          택시             [정기] 고속/시외/시내버스         단독(없음)
26340                         자가용                           N            배우자
26341                         자가용                           N             자녀

              travel_activity
26337                 회의참가/시찰
26338             음식관광, 휴식/휴양
26339          시티투어, 가족/친지 방문
26340  자연 및 풍경감상, 음식관광, 휴식/휴양
26341         음식관광, 휴식/휴양, 쇼핑

C:\Users\playdata2\AppData\Local\Temp\ipykernel_24448\965303395.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tour4 = tour4.fillna('N')

In [55]:
tour4

,with_pet,gender,age_group,trip1_visit1_area,trip1_stay1_area,trip1_stay1_type,trip1_visit2_area,trip1_transport(city2city),trip1_transport(incity1),trip1_transport(incity1),companion_type,travel_activity
0,미동반,남자,40대,32030,32030,콘도미니엄/리조트,32030,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문"
1,미동반,남자,30대,32030,N,N,32030,자가용,자가용,N,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문"
2,미동반,남자,20대,38090,N,N,38090,철도,택시,[정기] 고속/시외/시내버스,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파"
3,미동반,남자,40대,31270,N,N,N,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양"
4,미동반,여자,60대,34060,N,N,N,도보,[부정기] 전세/관광버스,N,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠"
...,...,...,...,...,...,...,...,...,...,...,...,...
26337,미동반,남자,40대,38110,38110,호텔,N,항공기,자가용,N,단독(없음),회의참가/시찰
26338,미동반,여자,20대,39010,N,N,N,자가용,자가용,N,친구,"음식관광, 휴식/휴양"
26339,미동반,여자,30대,31010,31010,가족/친지집,N,항공기,택시,[정기] 고속/시외/시내버스,단독(없음),"시티투어, 가족/친지 방문"
26340,미동반,남자,50대,39010,N,N,N,자가용,자가용,N,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양"
26341,미동반,여자,30대,39010,N,N,N,자가용,자가용,N,자녀,"음식관광, 휴식/휴양, 쇼핑"

In [ ]:
import pandas as pd

# 1. 새 시군구 코드 데이터 로드
code_df = pd.read_csv('./data/sigungu_code.csv', dtype=str)

# 2. 5자리 결합 코드 생성 (시도코드 2자리 + 시군구코드 3자리)
# 예: '11' + '010' -> '11010'
code_df['full_code'] = code_df['시도코드'].str.zfill(2) + code_df['시군구코드'].str.zfill(3)

# 3. 매핑용 딕셔너리 생성
sido_map = dict(zip(code_df['full_code'], code_df['시도명']))
sigungu_map = dict(zip(code_df['full_code'], code_df['시군구명']))

# 4. 변환 대상 컬럼 설정
target_cols = ['trip1_visit1_area', 'trip1_stay1_area', 'trip1_visit2_area']

for col in target_cols:
    if col in tour4.columns:
        # tour4의 데이터를 5자리 문자열로 변환
        # 'N'이거나 비어있는 값은 제외하고 처리
        tour4[col] = tour4[col].apply(
            lambda x: str(int(float(x))).zfill(5) if str(x).replace('.','').isdigit() else 'N'
        )
        
        # 새로운 컬럼명 정의 (sido, sigungu)
        base_name = col.replace('_area', '')
        sido_col = f"{base_name}_sido"
        sigungu_col = f"{base_name}_sigungu"
        
        # 매핑 수행
        tour4[sido_col] = tour4[col].map(sido_map).fillna('N')
        tour4[sigungu_col] = tour4[col].map(sigungu_map).fillna('N')

new_geo_cols = [c for c in tour4.columns if '_sido' in c or '_sigungu' in c]
print("✅ 5자리 결합 코드 기준 매핑 완료!")

# 'N'이 아닌 실제 데이터가 매핑되었는지 샘플 확인
success_sample = tour4[tour4['trip1_visit1_sido'] != 'N'][new_geo_cols].head()

if not success_sample.empty:
    print(f" 매핑 성공 컬럼: {new_geo_cols}")
    print("\n 변환 결과 샘플 (상위 5행):")
    print(success_sample)
else:
    print("\n 아직 'N'만 출력된다면, tour4['trip1_visit1_area']의 실제 값 하나만 출력해서 확인해봐야 합니다.")
    print("예: ", tour4['trip1_visit1_area'].unique()[:5])

✅ 5자리 결합 코드 기준 매핑 완료!
📊 매핑 성공 컬럼: ['trip1_visit1_sido', 'trip1_visit1_sigungu', 'trip1_stay1_sido', 'trip1_stay1_sigungu', 'trip1_visit2_sido', 'trip1_visit2_sigungu']

👀 변환 결과 샘플 (상위 5행):
  trip1_visit1_sido trip1_visit1_sigungu trip1_stay1_sido trip1_stay1_sigungu  \
0               강원도                  강릉시              강원도                 강릉시
1               강원도                  강릉시                N                   N
2              경상남도                  거제시                N                   N
3               경기도                  포천시                N                   N
4              충청남도                  논산시                N                   N

  trip1_visit2_sido trip1_visit2_sigungu
0               강원도                  강릉시
1               강원도                  강릉시
2              경상남도                  거제시
3                 N                    N
4                 N                    N

In [65]:
tour4

,with_pet,gender,age_group,trip1_visit1_area,trip1_stay1_area,trip1_stay1_type,trip1_visit2_area,trip1_transport(city2city),trip1_transport(incity1),trip1_transport(incity1),companion_type,travel_activity,trip1_visit1_sido,trip1_visit1_sigungu,trip1_stay1_sido,trip1_stay1_sigungu,trip1_visit2_sido,trip1_visit2_sigungu
0,미동반,남자,40대,32030,32030,콘도미니엄/리조트,32030,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문",강원도,강릉시,강원도,강릉시,강원도,강릉시
1,미동반,남자,30대,32030,N,N,32030,자가용,자가용,N,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문",강원도,강릉시,N,N,강원도,강릉시
2,미동반,남자,20대,38090,N,N,38090,철도,택시,[정기] 고속/시외/시내버스,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파",경상남도,거제시,N,N,경상남도,거제시
3,미동반,남자,40대,31270,N,N,N,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양",경기도,포천시,N,N,N,N
4,미동반,여자,60대,34060,N,N,N,도보,[부정기] 전세/관광버스,N,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠",충청남도,논산시,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26337,미동반,남자,40대,38110,38110,호텔,N,항공기,자가용,N,단독(없음),회의참가/시찰,경상남도,창원시,경상남도,창원시,N,N
26338,미동반,여자,20대,39010,N,N,N,자가용,자가용,N,친구,"음식관광, 휴식/휴양",제주특별자치도,제주시,N,N,N,N
26339,미동반,여자,30대,31010,31010,가족/친지집,N,항공기,택시,[정기] 고속/시외/시내버스,단독(없음),"시티투어, 가족/친지 방문",경기도,수원시,경기도,수원시,N,N
26340,미동반,남자,50대,39010,N,N,N,자가용,자가용,N,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양",제주특별자치도,제주시,N,N,N,N
26341,미동반,여자,30대,39010,N,N,N,자가용,자가용,N,자녀,"음식관광, 휴식/휴양, 쇼핑",제주특별자치도,제주시,N,N,N,N

In [66]:
tour_survey = tour4.copy()

In [68]:
tour_survey.drop(columns=['trip1_visit2_sido', 'trip1_visit2_area', 'trip1_visit2_sigungu'], inplace=True, errors='ignore')

In [69]:
tour_survey.columns = tour_survey.columns.str.replace('1', '', regex=False)

print(tour_survey.columns)

Index(['with_pet', 'gender', 'age_group', 'trip_visit_area', 'trip_stay_area',
       'trip_stay_type', 'trip_transport(city2city)', 'trip_transport(incity)',
       'trip_transport(incity)', 'companion_type', 'travel_activity',
       'trip_visit_sido', 'trip_visit_sigungu', 'trip_stay_sido',
       'trip_stay_sigungu'],
      dtype='object')

In [70]:
import pandas as pd

# 1. 현재 컬럼명을 리스트로 가져오기
cols = list(tour_survey.columns)

# 2. 중복된 이름에 숫자를 붙이기
count = {}
new_cols = []

for col in cols:
    if col in count:
        count[col] += 1
        new_cols.append(f"{col}{count[col]}")
    else:
        count[col] = 1
        new_cols.append(col)

# 3. 변경된 컬럼명 적용
tour_survey.columns = new_cols

# 4. 결과 확인
print(tour_survey.columns)

Index(['with_pet', 'gender', 'age_group', 'trip_visit_area', 'trip_stay_area',
       'trip_stay_type', 'trip_transport(city2city)', 'trip_transport(incity)',
       'trip_transport(incity)2', 'companion_type', 'travel_activity',
       'trip_visit_sido', 'trip_visit_sigungu', 'trip_stay_sido',
       'trip_stay_sigungu'],
      dtype='object')

In [71]:
tour_survey

,with_pet,gender,age_group,trip_visit_area,trip_stay_area,trip_stay_type,trip_transport(city2city),trip_transport(incity),trip_transport(incity)2,companion_type,travel_activity,trip_visit_sido,trip_visit_sigungu,trip_stay_sido,trip_stay_sigungu
0,미동반,남자,40대,32030,32030,콘도미니엄/리조트,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 쇼핑, 드라마 촬영지 방문",강원도,강릉시,강원도,강릉시
1,미동반,남자,30대,32030,N,N,자가용,자가용,N,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양, 온천/스파, 드라마 촬영지 방문",강원도,강릉시,N,N
2,미동반,남자,20대,38090,N,N,철도,택시,[정기] 고속/시외/시내버스,친구,"자연 및 풍경감상, 음식관광, 테마파크/동식물원, 휴식/휴양, 온천/스파",경상남도,거제시,N,N
3,미동반,남자,40대,31270,N,N,자가용,자가용,도보,배우자,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠, 휴식/휴양",경기도,포천시,N,N
4,미동반,여자,60대,34060,N,N,도보,[부정기] 전세/관광버스,N,친목 단체/모임,"자연 및 풍경감상, 음식관광, 야외 스포츠/레포츠",충청남도,논산시,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26337,미동반,남자,40대,38110,38110,호텔,항공기,자가용,N,단독(없음),회의참가/시찰,경상남도,창원시,경상남도,창원시
26338,미동반,여자,20대,39010,N,N,자가용,자가용,N,친구,"음식관광, 휴식/휴양",제주특별자치도,제주시,N,N
26339,미동반,여자,30대,31010,31010,가족/친지집,항공기,택시,[정기] 고속/시외/시내버스,단독(없음),"시티투어, 가족/친지 방문",경기도,수원시,경기도,수원시
26340,미동반,남자,50대,39010,N,N,자가용,자가용,N,배우자,"자연 및 풍경감상, 음식관광, 휴식/휴양",제주특별자치도,제주시,N,N
26341,미동반,여자,30대,39010,N,N,자가용,자가용,N,자녀,"음식관광, 휴식/휴양, 쇼핑",제주특별자치도,제주시,N,N

In [ ]:
tour_survey.to_pickle("./tour_survey_final.pkl")